    oauth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://{subdomain}.{domain}.com/oauth/authorizations/new
          tokenUrl: https://{subdomain}.{domain}.com/oauth/tokens
          scopes:
            read: Grants read access
            write: Grants write access
            impersonate: Impersonate end users
  - oauth: []
