      x-speakeasy-pagination:
        type: cursor
        inputs:
          - name: page[after]
            in: parameters
            type: cursor
        outputs:
          nextCursor: $.meta.after_cursor
        - name: page[size]
          in: query
          description: Number of records per page (required for cursor pagination)
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 100
        - name: page[after]
          in: query
          description: Cursor for pagination (opaque string)
          required: false
          schema:
            type: string
      x-speakeasy-pagination:
        type: cursor
        inputs:
          - name: page[after]
            in: parameters
            type: cursor
        outputs:
          nextCursor: $.meta.after_cursor
      x-speakeasy-pagination:
        type: cursor
        inputs:
          - name: page[after]
            in: parameters
            type: cursor
        outputs:
          nextCursor: $.meta.after_cursor
      parameters:
        - $ref: "#/components/parameters/SuspendedTicketsSortBy"
        - $ref: "#/components/parameters/SuspendedTicketsSortOrder"
        - name: page[size]
          in: query
          description: Number of records per page (required for cursor pagination)
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 100
        - name: page[after]
          in: query
          description: Cursor for pagination (opaque string)
          required: false
          schema:
            type: string
      get:
        operationId: ListSuspendedTickets
        tags:
          - Suspended Tickets
        summary: List Suspended Tickets
      x-speakeasy-pagination:
        type: cursor
        inputs:
          - name: page[after]
            in: parameters
            type: cursor
        outputs:
          nextCursor: $.meta.after_cursor
