"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from typing import List, Optional
from zendesk.errors import ZendeskError
from zendesk.models import (
    batcherroritem as models_batcherroritem,
    batchjobresponse as models_batchjobresponse,
)
from zendesk.types import BaseModel


class BatchJobResponseErrorData(BaseModel):
    errors: Optional[List[models_batcherroritem.BatchErrorItem]] = None

    results: Optional[models_batchjobresponse.BatchJobResponseResults] = None

    status: Optional[models_batchjobresponse.BatchJobResponseStatus] = None


@dataclass(unsafe_hash=True)
class BatchJobResponseError(ZendeskError):
    data: BatchJobResponseErrorData = field(hash=False)

    def __init__(
        self,
        data: BatchJobResponseErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
