"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class AccountSettingsStatisticsObjectTypedDict(TypedDict):
    r"""Account statistics settings. See [Statistics](#statistics)"""

    forum: NotRequired[bool]
    rule_usage: NotRequired[bool]
    search: NotRequired[bool]


class AccountSettingsStatisticsObject(BaseModel):
    r"""Account statistics settings. See [Statistics](#statistics)"""

    forum: Optional[bool] = None

    rule_usage: Optional[bool] = None

    search: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["forum", "rule_usage", "search"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
