"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class AccountSettingsBrandingObjectTypedDict(TypedDict):
    r"""Branding settings. See [Branding](#branding)"""

    favicon_url: NotRequired[Nullable[str]]
    header_color: NotRequired[str]
    header_logo_url: NotRequired[Nullable[str]]
    page_background_color: NotRequired[str]
    tab_background_color: NotRequired[str]
    text_color: NotRequired[str]


class AccountSettingsBrandingObject(BaseModel):
    r"""Branding settings. See [Branding](#branding)"""

    favicon_url: OptionalNullable[str] = UNSET

    header_color: Optional[str] = None

    header_logo_url: OptionalNullable[str] = UNSET

    page_background_color: Optional[str] = None

    tab_background_color: Optional[str] = None

    text_color: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "favicon_url",
                "header_color",
                "header_logo_url",
                "page_background_color",
                "tab_background_color",
                "text_color",
            ]
        )
        nullable_fields = set(["favicon_url", "header_logo_url"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
