"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class AccountSettingsRoutingObjectTypedDict(TypedDict):
    r"""Configuration for routing. See [Routing](#routing)"""

    autorouting_tag: NotRequired[str]
    enabled: NotRequired[bool]
    max_email_capacity: NotRequired[int]
    max_messaging_capacity: NotRequired[int]
    reassignment_messaging_enabled: NotRequired[bool]
    reassignment_messaging_timeout: NotRequired[int]
    reassignment_talk_timeout: NotRequired[int]


class AccountSettingsRoutingObject(BaseModel):
    r"""Configuration for routing. See [Routing](#routing)"""

    autorouting_tag: Optional[str] = None

    enabled: Optional[bool] = None

    max_email_capacity: Optional[int] = None

    max_messaging_capacity: Optional[int] = None

    reassignment_messaging_enabled: Optional[bool] = None

    reassignment_messaging_timeout: Optional[int] = None

    reassignment_talk_timeout: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "autorouting_tag",
                "enabled",
                "max_email_capacity",
                "max_messaging_capacity",
                "reassignment_messaging_enabled",
                "reassignment_messaging_timeout",
                "reassignment_talk_timeout",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
