"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class AccountSettingsSideConversationsObjectTypedDict(TypedDict):
    r"""Side conversations settings"""

    email_channel: NotRequired[bool]
    msteams_channel: NotRequired[bool]
    show_in_context_panel: NotRequired[bool]
    slack_channel: NotRequired[bool]
    tickets_channel: NotRequired[bool]


class AccountSettingsSideConversationsObject(BaseModel):
    r"""Side conversations settings"""

    email_channel: Optional[bool] = None

    msteams_channel: Optional[bool] = None

    show_in_context_panel: Optional[bool] = None

    slack_channel: Optional[bool] = None

    tickets_channel: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "email_channel",
                "msteams_channel",
                "show_in_context_panel",
                "slack_channel",
                "tickets_channel",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
