"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class AccountSettingsAPIObjectTypedDict(TypedDict):
    r"""API configuration options. See [API](#api)"""

    accepted_api_agreement: NotRequired[bool]
    api_password_access: NotRequired[str]
    api_token_access: NotRequired[str]


class AccountSettingsAPIObject(BaseModel):
    r"""API configuration options. See [API](#api)"""

    accepted_api_agreement: Optional[bool] = None

    api_password_access: Optional[str] = None

    api_token_access: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["accepted_api_agreement", "api_password_access", "api_token_access"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
