"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class AccountSettingsCrossSellObjectTypedDict(TypedDict):
    r"""Cross Sell settings"""

    show_chat_tooltip: NotRequired[bool]
    xsell_source: NotRequired[Nullable[str]]


class AccountSettingsCrossSellObject(BaseModel):
    r"""Cross Sell settings"""

    show_chat_tooltip: Optional[bool] = None

    xsell_source: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["show_chat_tooltip", "xsell_source"])
        nullable_fields = set(["xsell_source"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
