"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class AccountSettingsChatObjectTypedDict(TypedDict):
    r"""Zendesk Chat settings. See [Chat](#chat)"""

    available: NotRequired[bool]
    enabled: NotRequired[bool]
    integrated: NotRequired[bool]
    maximum_request_count: NotRequired[int]
    welcome_message: NotRequired[str]


class AccountSettingsChatObject(BaseModel):
    r"""Zendesk Chat settings. See [Chat](#chat)"""

    available: Optional[bool] = None

    enabled: Optional[bool] = None

    integrated: Optional[bool] = None

    maximum_request_count: Optional[int] = None

    welcome_message: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "available",
                "enabled",
                "integrated",
                "maximum_request_count",
                "welcome_message",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
