"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class AccountSettingsOnboardingObjectTypedDict(TypedDict):
    r"""Onboarding settings"""

    checklist_onboarding_version: NotRequired[int]
    onboarding_segments: NotRequired[Nullable[str]]
    product_sign_up: NotRequired[Nullable[str]]


class AccountSettingsOnboardingObject(BaseModel):
    r"""Onboarding settings"""

    checklist_onboarding_version: Optional[int] = None

    onboarding_segments: OptionalNullable[str] = UNSET

    product_sign_up: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["checklist_onboarding_version", "onboarding_segments", "product_sign_up"]
        )
        nullable_fields = set(["onboarding_segments", "product_sign_up"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
