"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class HostTypedDict(TypedDict):
    name: NotRequired[str]
    url: NotRequired[str]


class Host(BaseModel):
    name: Optional[str] = None

    url: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name", "url"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class AccountSettingsCdnObjectTypedDict(TypedDict):
    r"""CDN settings"""

    cdn_provider: NotRequired[str]
    fallback_cdn_provider: NotRequired[str]
    hosts: NotRequired[List[HostTypedDict]]


class AccountSettingsCdnObject(BaseModel):
    r"""CDN settings"""

    cdn_provider: Optional[str] = None

    fallback_cdn_provider: Optional[str] = None

    hosts: Optional[List[Host]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["cdn_provider", "fallback_cdn_provider", "hosts"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
