"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class AccountSettingsTicketObjectTypedDict(TypedDict):
    r"""Ticket settings. See [Tickets](#tickets)"""

    accepted_new_collaboration_tos: NotRequired[bool]
    agent_collision: NotRequired[bool]
    agent_invitation_enabled: NotRequired[bool]
    agent_ticket_deletion: NotRequired[bool]
    allow_group_reset: NotRequired[bool]
    assign_default_organization: NotRequired[bool]
    assign_tickets_upon_solve: NotRequired[bool]
    auto_translation_enabled: NotRequired[bool]
    auto_updated_ccs_followers_rules: NotRequired[bool]
    chat_sla_enablement: NotRequired[bool]
    collaboration: NotRequired[bool]
    comments_public_by_default: NotRequired[bool]
    default_solved_ticket_reassignment_strategy: NotRequired[str]
    email_attachments: NotRequired[bool]
    emoji_autocompletion: NotRequired[bool]
    follower_and_email_cc_collaborations: NotRequired[bool]
    has_color_text: NotRequired[bool]
    is_first_comment_private_enabled: NotRequired[bool]
    light_agent_email_ccs_allowed: NotRequired[bool]
    list_empty_views: NotRequired[bool]
    list_newest_comments_first: NotRequired[bool]
    markdown_ticket_comments: NotRequired[bool]
    maximum_personal_views_to_list: NotRequired[int]
    modern_ticket_reassignment: NotRequired[bool]
    private_attachments: NotRequired[bool]
    rich_text_comments: NotRequired[bool]
    show_modern_ticket_reassignment: NotRequired[bool]
    status_hold: NotRequired[bool]
    tagging: NotRequired[bool]
    using_skill_based_routing: NotRequired[bool]


class AccountSettingsTicketObject(BaseModel):
    r"""Ticket settings. See [Tickets](#tickets)"""

    accepted_new_collaboration_tos: Optional[bool] = None

    agent_collision: Optional[bool] = None

    agent_invitation_enabled: Optional[bool] = None

    agent_ticket_deletion: Optional[bool] = None

    allow_group_reset: Optional[bool] = None

    assign_default_organization: Optional[bool] = None

    assign_tickets_upon_solve: Optional[bool] = None

    auto_translation_enabled: Optional[bool] = None

    auto_updated_ccs_followers_rules: Optional[bool] = None

    chat_sla_enablement: Optional[bool] = None

    collaboration: Optional[bool] = None

    comments_public_by_default: Optional[bool] = None

    default_solved_ticket_reassignment_strategy: Optional[str] = None

    email_attachments: Optional[bool] = None

    emoji_autocompletion: Optional[bool] = None

    follower_and_email_cc_collaborations: Optional[bool] = None

    has_color_text: Optional[bool] = None

    is_first_comment_private_enabled: Optional[bool] = None

    light_agent_email_ccs_allowed: Optional[bool] = None

    list_empty_views: Optional[bool] = None

    list_newest_comments_first: Optional[bool] = None

    markdown_ticket_comments: Optional[bool] = None

    maximum_personal_views_to_list: Optional[int] = None

    modern_ticket_reassignment: Optional[bool] = None

    private_attachments: Optional[bool] = None

    rich_text_comments: Optional[bool] = None

    show_modern_ticket_reassignment: Optional[bool] = None

    status_hold: Optional[bool] = None

    tagging: Optional[bool] = None

    using_skill_based_routing: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "accepted_new_collaboration_tos",
                "agent_collision",
                "agent_invitation_enabled",
                "agent_ticket_deletion",
                "allow_group_reset",
                "assign_default_organization",
                "assign_tickets_upon_solve",
                "auto_translation_enabled",
                "auto_updated_ccs_followers_rules",
                "chat_sla_enablement",
                "collaboration",
                "comments_public_by_default",
                "default_solved_ticket_reassignment_strategy",
                "email_attachments",
                "emoji_autocompletion",
                "follower_and_email_cc_collaborations",
                "has_color_text",
                "is_first_comment_private_enabled",
                "light_agent_email_ccs_allowed",
                "list_empty_views",
                "list_newest_comments_first",
                "markdown_ticket_comments",
                "maximum_personal_views_to_list",
                "modern_ticket_reassignment",
                "private_attachments",
                "rich_text_comments",
                "show_modern_ticket_reassignment",
                "status_hold",
                "tagging",
                "using_skill_based_routing",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
