"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class AccountSettingsLimitsObjectTypedDict(TypedDict):
    r"""Account limits configuration. See [Limits](#limits)"""

    attachment_size: NotRequired[int]


class AccountSettingsLimitsObject(BaseModel):
    r"""Account limits configuration. See [Limits](#limits)"""

    attachment_size: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["attachment_size"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
