"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .activityobject import ActivityObject, ActivityObjectTypedDict
from pydantic import model_serializer
from typing import Any, Dict, List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class ActivitiesResponseTypedDict(TypedDict):
    activities: NotRequired[List[ActivityObjectTypedDict]]
    actors: NotRequired[List[Dict[str, Any]]]
    count: NotRequired[int]
    next_page: NotRequired[Nullable[str]]
    previous_page: NotRequired[Nullable[str]]
    users: NotRequired[List[Dict[str, Any]]]


class ActivitiesResponse(BaseModel):
    activities: Optional[List[ActivityObject]] = None

    actors: Optional[List[Dict[str, Any]]] = None

    count: Optional[int] = None

    next_page: OptionalNullable[str] = UNSET

    previous_page: OptionalNullable[str] = UNSET

    users: Optional[List[Dict[str, Any]]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["activities", "actors", "count", "next_page", "previous_page", "users"]
        )
        nullable_fields = set(["next_page", "previous_page"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
