"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .approvalrequestuser import ApprovalRequestUser, ApprovalRequestUserTypedDict
from datetime import datetime
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class ApprovalRequestDecisionTypedDict(TypedDict):
    decided_at: NotRequired[datetime]
    r"""The time the decision was made"""
    decided_by_user: NotRequired[ApprovalRequestUserTypedDict]
    decision_notes: NotRequired[str]
    r"""Notes for the decision"""
    id: NotRequired[str]
    r"""Unique identifier for the decision"""
    status: NotRequired[str]
    r"""Status of the decision"""


class ApprovalRequestDecision(BaseModel):
    decided_at: Optional[datetime] = None
    r"""The time the decision was made"""

    decided_by_user: Optional[ApprovalRequestUser] = None

    decision_notes: Optional[str] = None
    r"""Notes for the decision"""

    id: Optional[str] = None
    r"""Unique identifier for the decision"""

    status: Optional[str] = None
    r"""Status of the decision"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["decided_at", "decided_by_user", "decision_notes", "id", "status"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
