"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .approvalrequestdecision import (
    ApprovalRequestDecision,
    ApprovalRequestDecisionTypedDict,
)
from .approvalrequestuser import ApprovalRequestUser, ApprovalRequestUserTypedDict
from .approvalticketdetails import ApprovalTicketDetails, ApprovalTicketDetailsTypedDict
from datetime import datetime
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class ApprovalRequestObjectApprovalRequestTypedDict(TypedDict):
    assignee_user: NotRequired[ApprovalRequestUserTypedDict]
    created_at: NotRequired[datetime]
    r"""The time the approval request was created"""
    created_by_user: NotRequired[ApprovalRequestUserTypedDict]
    decided_at: NotRequired[Nullable[datetime]]
    r"""The time at which the approver submitted a decision about the request."""
    decisions: NotRequired[List[ApprovalRequestDecisionTypedDict]]
    r"""List of decisions for the approval request"""
    id: NotRequired[str]
    r"""Unique identifier for the approval request"""
    message: NotRequired[str]
    r"""Details for the approval request"""
    status: NotRequired[str]
    r"""Current status of the approval request"""
    subject: NotRequired[str]
    r"""Subject for the approval request"""
    ticket_details: NotRequired[ApprovalTicketDetailsTypedDict]
    withdrawn_reason: NotRequired[Nullable[str]]
    r"""Reason for withdrawing the approval request"""


class ApprovalRequestObjectApprovalRequest(BaseModel):
    assignee_user: Optional[ApprovalRequestUser] = None

    created_at: Optional[datetime] = None
    r"""The time the approval request was created"""

    created_by_user: Optional[ApprovalRequestUser] = None

    decided_at: OptionalNullable[datetime] = UNSET
    r"""The time at which the approver submitted a decision about the request."""

    decisions: Optional[List[ApprovalRequestDecision]] = None
    r"""List of decisions for the approval request"""

    id: Optional[str] = None
    r"""Unique identifier for the approval request"""

    message: Optional[str] = None
    r"""Details for the approval request"""

    status: Optional[str] = None
    r"""Current status of the approval request"""

    subject: Optional[str] = None
    r"""Subject for the approval request"""

    ticket_details: Optional[ApprovalTicketDetails] = None

    withdrawn_reason: OptionalNullable[str] = UNSET
    r"""Reason for withdrawing the approval request"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "assignee_user",
                "created_at",
                "created_by_user",
                "decided_at",
                "decisions",
                "id",
                "message",
                "status",
                "subject",
                "ticket_details",
                "withdrawn_reason",
            ]
        )
        nullable_fields = set(["decided_at", "withdrawn_reason"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class ApprovalRequestObjectTypedDict(TypedDict):
    approval_request: NotRequired[ApprovalRequestObjectApprovalRequestTypedDict]


class ApprovalRequestObject(BaseModel):
    approval_request: Optional[ApprovalRequestObjectApprovalRequest] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["approval_request"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
