"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class ApprovalRequestCreateRequestTypedDict(TypedDict):
    assignee_user: NotRequired[int]
    r"""User id of the request approver"""
    message: NotRequired[str]
    r"""Details for the approval request"""
    subject: NotRequired[str]
    r"""Subject for the approval request"""
    ticket_id: NotRequired[int]
    r"""Ticket id to attach the approval request to"""
    workflow_instance_id: NotRequired[str]
    r"""Workflow instance id for the approval request"""


class ApprovalRequestCreateRequest(BaseModel):
    assignee_user: Optional[int] = None
    r"""User id of the request approver"""

    message: Optional[str] = None
    r"""Details for the approval request"""

    subject: Optional[str] = None
    r"""Subject for the approval request"""

    ticket_id: Optional[int] = None
    r"""Ticket id to attach the approval request to"""

    workflow_instance_id: Optional[str] = None
    r"""Workflow instance id for the approval request"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["assignee_user", "message", "subject", "ticket_id", "workflow_instance_id"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
