"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .customobjectrecord import CustomObjectRecord, CustomObjectRecordTypedDict
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class ApprovalWorkflowInstanceObjectTypedDict(TypedDict):
    custom_object_record: NotRequired[CustomObjectRecordTypedDict]


class ApprovalWorkflowInstanceObject(BaseModel):
    custom_object_record: Optional[CustomObjectRecord] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["custom_object_record"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
