"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class ApprovalRequestsSearchResponseApprovalRequestTypedDict(TypedDict):
    approval_workflow_instance_id: NotRequired[str]
    r"""Unique identifier for the approval workflow instance. See [Approval Workflow Instances](/api-reference/ticketing/approvals/approval_workflow_instances/#approval-workflow-instances)"""
    created_at: NotRequired[datetime]
    r"""The time the approval request was created was created"""
    created_by_name: NotRequired[str]
    r"""Name of the user that created the approval request"""
    id: NotRequired[str]
    r"""Unique identifier for the approval request"""
    message: NotRequired[str]
    r"""Details for the approval request"""
    requester_name: NotRequired[str]
    r"""Name of the user that can make a decision on the approval request"""
    status: NotRequired[str]
    r"""Current status of the approval request"""
    subject: NotRequired[str]
    r"""Subject for the approval request"""


class ApprovalRequestsSearchResponseApprovalRequest(BaseModel):
    approval_workflow_instance_id: Optional[str] = None
    r"""Unique identifier for the approval workflow instance. See [Approval Workflow Instances](/api-reference/ticketing/approvals/approval_workflow_instances/#approval-workflow-instances)"""

    created_at: Optional[datetime] = None
    r"""The time the approval request was created was created"""

    created_by_name: Optional[str] = None
    r"""Name of the user that created the approval request"""

    id: Optional[str] = None
    r"""Unique identifier for the approval request"""

    message: Optional[str] = None
    r"""Details for the approval request"""

    requester_name: Optional[str] = None
    r"""Name of the user that can make a decision on the approval request"""

    status: Optional[str] = None
    r"""Current status of the approval request"""

    subject: Optional[str] = None
    r"""Subject for the approval request"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "approval_workflow_instance_id",
                "created_at",
                "created_by_name",
                "id",
                "message",
                "requester_name",
                "status",
                "subject",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ApprovalRequestsSearchResponseTypedDict(TypedDict):
    after_cursor: NotRequired[Nullable[str]]
    r"""Cursor for the next page of results"""
    after_url: NotRequired[Nullable[str]]
    r"""URL for the next page of results"""
    approval_requests: NotRequired[
        List[ApprovalRequestsSearchResponseApprovalRequestTypedDict]
    ]
    before_cursor: NotRequired[Nullable[str]]
    r"""Cursor for the previous page of results"""
    before_url: NotRequired[Nullable[str]]
    r"""URL for the previous page of results"""


class ApprovalRequestsSearchResponse(BaseModel):
    after_cursor: OptionalNullable[str] = UNSET
    r"""Cursor for the next page of results"""

    after_url: OptionalNullable[str] = UNSET
    r"""URL for the next page of results"""

    approval_requests: Optional[List[ApprovalRequestsSearchResponseApprovalRequest]] = (
        None
    )

    before_cursor: OptionalNullable[str] = UNSET
    r"""Cursor for the previous page of results"""

    before_url: OptionalNullable[str] = UNSET
    r"""URL for the previous page of results"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "after_cursor",
                "after_url",
                "approval_requests",
                "before_cursor",
                "before_url",
            ]
        )
        nullable_fields = set(
            ["after_cursor", "after_url", "before_cursor", "before_url"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
