"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class AssigneeFieldAssignableSearchGroupObjectTypedDict(TypedDict):
    id: NotRequired[int]
    r"""Group ID"""
    name: NotRequired[str]
    r"""Name of the group"""


class AssigneeFieldAssignableSearchGroupObject(BaseModel):
    id: Optional[int] = None
    r"""Group ID"""

    name: Optional[str] = None
    r"""Name of the group"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
