"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class AssigneeFieldAssignableAgentObjectTypedDict(TypedDict):
    avatar_url: NotRequired[Nullable[str]]
    r"""URL of Agent's avatar"""
    id: NotRequired[int]
    r"""Agent Support ID"""
    name: NotRequired[str]
    r"""Name of the agent"""


class AssigneeFieldAssignableAgentObject(BaseModel):
    avatar_url: OptionalNullable[str] = UNSET
    r"""URL of Agent's avatar"""

    id: Optional[int] = None
    r"""Agent Support ID"""

    name: Optional[str] = None
    r"""Name of the agent"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["avatar_url", "id", "name"])
        nullable_fields = set(["avatar_url"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
