"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .automationobject import AutomationObject, AutomationObjectTypedDict
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class AutomationsResponseTypedDict(TypedDict):
    automations: NotRequired[List[AutomationObjectTypedDict]]
    count: NotRequired[int]
    next_page: NotRequired[Nullable[str]]
    previous_page: NotRequired[Nullable[str]]


class AutomationsResponse(BaseModel):
    automations: Optional[List[AutomationObject]] = None

    count: Optional[int] = None

    next_page: OptionalNullable[str] = UNSET

    previous_page: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["automations", "count", "next_page", "previous_page"])
        nullable_fields = set(["next_page", "previous_page"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
