"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL
from zendesk.utils import FieldMetadata, QueryParamMetadata, RequestMetadata


class AutocompleteProblemsRequestBodyTypedDict(TypedDict):
    text: NotRequired[str]
    r"""The text to search for"""


class AutocompleteProblemsRequestBody(BaseModel):
    text: Optional[str] = None
    r"""The text to search for"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["text"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class AutocompleteProblemsRequestTypedDict(TypedDict):
    text: NotRequired[str]
    r"""The text to search for"""
    request_body: NotRequired[AutocompleteProblemsRequestBodyTypedDict]


class AutocompleteProblemsRequest(BaseModel):
    text: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The text to search for"""

    request_body: Annotated[
        Optional[AutocompleteProblemsRequestBody],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["text", "RequestBody"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
