"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


BasicAuthAuthenticationType = Literal["basic_auth",]


class BasicAuthAuthenticationDataTypedDict(TypedDict):
    username: str
    r"""Username for basic authentication"""
    password: NotRequired[str]
    r"""Password for basic authentication"""


class BasicAuthAuthenticationData(BaseModel):
    username: str
    r"""Username for basic authentication"""

    password: Optional[str] = None
    r"""Password for basic authentication"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["password"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class BasicAuthAuthenticationTypedDict(TypedDict):
    r"""Basic authentication configuration"""

    type: BasicAuthAuthenticationType
    data: BasicAuthAuthenticationDataTypedDict


class BasicAuthAuthentication(BaseModel):
    r"""Basic authentication configuration"""

    type: BasicAuthAuthenticationType

    data: BasicAuthAuthenticationData
