"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .batcherroritem import BatchErrorItem, BatchErrorItemTypedDict
from .triggercategory import TriggerCategory, TriggerCategoryTypedDict
from .triggerobject import TriggerObject, TriggerObjectTypedDict
from pydantic import model_serializer
from typing import List, Literal, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class BatchJobResponseResultsTypedDict(TypedDict):
    trigger_categories: NotRequired[List[TriggerCategoryTypedDict]]
    triggers: NotRequired[List[TriggerObjectTypedDict]]


class BatchJobResponseResults(BaseModel):
    trigger_categories: Optional[List[TriggerCategory]] = None

    triggers: Optional[List[TriggerObject]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["trigger_categories", "triggers"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


BatchJobResponseStatus = Literal[
    "complete",
    "failed",
]


class BatchJobResponseTypedDict(TypedDict):
    errors: NotRequired[List[BatchErrorItemTypedDict]]
    results: NotRequired[BatchJobResponseResultsTypedDict]
    status: NotRequired[BatchJobResponseStatus]


class BatchJobResponse(BaseModel):
    errors: Optional[List[BatchErrorItem]] = None

    results: Optional[BatchJobResponseResults] = None

    status: Optional[BatchJobResponseStatus] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["errors", "results", "status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
