"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


BearerTokenAuthenticationType = Literal["bearer_token",]


class BearerTokenAuthenticationDataTypedDict(TypedDict):
    token: NotRequired[str]
    r"""Bearer token for authentication"""


class BearerTokenAuthenticationData(BaseModel):
    token: Optional[str] = None
    r"""Bearer token for authentication"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["token"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class BearerTokenAuthenticationTypedDict(TypedDict):
    r"""Bearer token authentication configuration"""

    type: BearerTokenAuthenticationType
    data: BearerTokenAuthenticationDataTypedDict


class BearerTokenAuthentication(BaseModel):
    r"""Bearer token authentication configuration"""

    type: BearerTokenAuthenticationType

    data: BearerTokenAuthenticationData
