"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .bookmarkobject import BookmarkObject, BookmarkObjectTypedDict
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class BookmarksResponseTypedDict(TypedDict):
    count: NotRequired[int]
    r"""the total record count"""
    next_page: NotRequired[Nullable[str]]
    r"""the URL of the next page"""
    previous_page: NotRequired[Nullable[str]]
    r"""the URL of the previous page"""
    bookmarks: NotRequired[List[BookmarkObjectTypedDict]]


class BookmarksResponse(BaseModel):
    count: Optional[int] = None
    r"""the total record count"""

    next_page: OptionalNullable[str] = UNSET
    r"""the URL of the next page"""

    previous_page: OptionalNullable[str] = UNSET
    r"""the URL of the previous page"""

    bookmarks: Optional[List[BookmarkObject]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["count", "next_page", "previous_page", "bookmarks"])
        nullable_fields = set(["next_page", "previous_page"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
