"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class BookmarkInputTypedDict(TypedDict):
    ticket_id: NotRequired[int]
    r"""The id of the ticket the bookmark is for."""


class BookmarkInput(BaseModel):
    ticket_id: Optional[int] = None
    r"""The id of the ticket the bookmark is for."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ticket_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
