"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class BrandAgentObjectTypedDict(TypedDict):
    brand_id: int
    r"""The id of a brand"""
    user_id: int
    r"""The id of an agent"""
    created_at: NotRequired[datetime]
    r"""The time the brand membership was created"""
    id: NotRequired[str]
    r"""Automatically assigned upon creation"""
    updated_at: NotRequired[datetime]
    r"""The time of the last update of the brand membership"""
    url: NotRequired[str]
    r"""The API url of this record"""


class BrandAgentObject(BaseModel):
    brand_id: int
    r"""The id of a brand"""

    user_id: int
    r"""The id of an agent"""

    created_at: Optional[datetime] = None
    r"""The time the brand membership was created"""

    id: Optional[str] = None
    r"""Automatically assigned upon creation"""

    updated_at: Optional[datetime] = None
    r"""The time of the last update of the brand membership"""

    url: Optional[str] = None
    r"""The API url of this record"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["created_at", "id", "updated_at", "url"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
