"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .skillbasedroutingattributevalueobject_input import (
    SkillBasedRoutingAttributeValueObjectInput,
    SkillBasedRoutingAttributeValueObjectInputTypedDict,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class AttributesTypedDict(TypedDict):
    r"""The attribute values to update. See [Attribute Values](#attribute-values)"""

    attribute_values: NotRequired[
        List[SkillBasedRoutingAttributeValueObjectInputTypedDict]
    ]


class Attributes(BaseModel):
    r"""The attribute values to update. See [Attribute Values](#attribute-values)"""

    attribute_values: Optional[List[SkillBasedRoutingAttributeValueObjectInput]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["attribute_values"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class BulkSkillBasedRoutingAttributeValueJobTypedDict(TypedDict):
    attributes: AttributesTypedDict
    r"""The attribute values to update. See [Attribute Values](#attribute-values)"""


class BulkSkillBasedRoutingAttributeValueJob(BaseModel):
    attributes: Attributes
    r"""The attribute values to update. See [Attribute Values](#attribute-values)"""
