"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing_extensions import TypedDict
from zendesk.types import BaseModel, Nullable, UNSET_SENTINEL


class ComplianceDeletionStatusObjectTypedDict(TypedDict):
    account_subdomain: str
    action: str
    application: str
    created_at: str
    executer_id: Nullable[int]
    user_id: int


class ComplianceDeletionStatusObject(BaseModel):
    account_subdomain: str

    action: str

    application: str

    created_at: str

    executer_id: Nullable[int]

    user_id: int

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
