"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class ConditionObjectTypedDict(TypedDict):
    field: NotRequired[str]
    r"""The name of a ticket field"""
    operator: NotRequired[str]
    r"""A comparison operator"""
    value: NotRequired[str]
    r"""The value of a ticket field"""


class ConditionObject(BaseModel):
    field: Optional[str] = None
    r"""The name of a ticket field"""

    operator: Optional[str] = None
    r"""A comparison operator"""

    value: Optional[str] = None
    r"""The value of a ticket field"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["field", "operator", "value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
