"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .conversationlogobject import ConversationLogObject, ConversationLogObjectTypedDict
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class ConversationLogResponseLinksTypedDict(TypedDict):
    next: NotRequired[str]
    prev: NotRequired[str]


class ConversationLogResponseLinks(BaseModel):
    next: Optional[str] = None

    prev: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["next", "prev"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ConversationLogResponseMetaTypedDict(TypedDict):
    after_cursor: NotRequired[str]
    before_cursor: NotRequired[str]
    has_more: NotRequired[bool]


class ConversationLogResponseMeta(BaseModel):
    after_cursor: Optional[str] = None

    before_cursor: Optional[str] = None

    has_more: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["after_cursor", "before_cursor", "has_more"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ConversationLogResponseTypedDict(TypedDict):
    events: NotRequired[List[ConversationLogObjectTypedDict]]
    links: NotRequired[ConversationLogResponseLinksTypedDict]
    meta: NotRequired[ConversationLogResponseMetaTypedDict]


class ConversationLogResponse(BaseModel):
    events: Optional[List[ConversationLogObject]] = None

    links: Optional[ConversationLogResponseLinks] = None

    meta: Optional[ConversationLogResponseMeta] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["events", "links", "meta"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
