"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .workspaceinput import WorkspaceInput, WorkspaceInputTypedDict
from .workspaceobject import WorkspaceObject, WorkspaceObjectTypedDict
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class CreateWorkspaceRequestTypedDict(TypedDict):
    workspace: NotRequired[WorkspaceInputTypedDict]


class CreateWorkspaceRequest(BaseModel):
    workspace: Optional[WorkspaceInput] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["workspace"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CreateWorkspaceResponseTypedDict(TypedDict):
    r"""Created workspace"""

    workspace: NotRequired[WorkspaceObjectTypedDict]


class CreateWorkspaceResponse(BaseModel):
    r"""Created workspace"""

    workspace: Optional[WorkspaceObject] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["workspace"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
