"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL
from zendesk.utils import FieldMetadata, QueryParamMetadata


class CreateOAuthTokenRequestTypedDict(TypedDict):
    client_id: NotRequired[int]
    r"""The id of the OAuth client"""
    global_client_id: NotRequired[int]
    r"""The id of the global OAuth client"""
    all: NotRequired[bool]
    r"""A boolean that returns all OAuth tokens in the account. Requires admin role"""


class CreateOAuthTokenRequest(BaseModel):
    client_id: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The id of the OAuth client"""

    global_client_id: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The id of the global OAuth client"""

    all: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""A boolean that returns all OAuth tokens in the account. Requires admin role"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["client_id", "global_client_id", "all"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
