"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL
from zendesk.utils import FieldMetadata, PathParamMetadata, RequestMetadata


class TicketFormStatusTypedDict(TypedDict):
    ticket_form_id: NotRequired[int]
    r"""The id of the ticket form"""


class TicketFormStatus(BaseModel):
    ticket_form_id: Optional[int] = None
    r"""The id of the ticket form"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ticket_form_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CreateTicketFormStatusesForCustomStatusRequestBodyTypedDict(TypedDict):
    ticket_form_status: NotRequired[List[TicketFormStatusTypedDict]]


class CreateTicketFormStatusesForCustomStatusRequestBody(BaseModel):
    ticket_form_status: Optional[List[TicketFormStatus]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ticket_form_status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CreateTicketFormStatusesForCustomStatusRequestTypedDict(TypedDict):
    custom_status_id: int
    r"""The id of the custom status"""
    request_body: NotRequired[
        CreateTicketFormStatusesForCustomStatusRequestBodyTypedDict
    ]


class CreateTicketFormStatusesForCustomStatusRequest(BaseModel):
    custom_status_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The id of the custom status"""

    request_body: Annotated[
        Optional[CreateTicketFormStatusesForCustomStatusRequestBody],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["RequestBody"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
