"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .webhookcreaterequest import WebhookCreateRequest, WebhookCreateRequestTypedDict
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL
from zendesk.utils import FieldMetadata, QueryParamMetadata, RequestMetadata


class CreateOrCloneWebhookRequestTypedDict(TypedDict):
    clone_webhook_id: NotRequired[str]
    r"""id of the webhook to clone. Only required if cloning a webhook."""
    webhook_create_request: NotRequired[WebhookCreateRequestTypedDict]
    r"""Webhook data (required when creating, not when cloning)"""


class CreateOrCloneWebhookRequest(BaseModel):
    clone_webhook_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""id of the webhook to clone. Only required if cloning a webhook."""

    webhook_create_request: Annotated[
        Optional[WebhookCreateRequest],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None
    r"""Webhook data (required when creating, not when cloning)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["clone_webhook_id", "WebhookCreateRequest"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
