"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .userobject import UserObject, UserObjectTypedDict
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class CursorBasedExportIncrementalUsersResponseTypedDict(TypedDict):
    after_cursor: NotRequired[Nullable[str]]
    after_url: NotRequired[Nullable[str]]
    before_cursor: NotRequired[Nullable[str]]
    before_url: NotRequired[Nullable[str]]
    end_of_stream: NotRequired[bool]
    users: NotRequired[List[UserObjectTypedDict]]


class CursorBasedExportIncrementalUsersResponse(BaseModel):
    after_cursor: OptionalNullable[str] = UNSET

    after_url: OptionalNullable[str] = UNSET

    before_cursor: OptionalNullable[str] = UNSET

    before_url: OptionalNullable[str] = UNSET

    end_of_stream: Optional[bool] = None

    users: Optional[List[UserObject]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "after_cursor",
                "after_url",
                "before_cursor",
                "before_url",
                "end_of_stream",
                "users",
            ]
        )
        nullable_fields = set(
            ["after_cursor", "after_url", "before_cursor", "before_url"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
