"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import ConfigDict, model_serializer
from typing import Any, Dict, List, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict
from zendesk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


CustomObjectRecordFilteredSearchConditionValue1TypedDict = TypeAliasType(
    "CustomObjectRecordFilteredSearchConditionValue1TypedDict", Union[str, int]
)


CustomObjectRecordFilteredSearchConditionValue1 = TypeAliasType(
    "CustomObjectRecordFilteredSearchConditionValue1", Union[str, int]
)


CustomObjectRecordFilteredSearchConditionValue2TypedDict = TypeAliasType(
    "CustomObjectRecordFilteredSearchConditionValue2TypedDict",
    Union[str, int, List[CustomObjectRecordFilteredSearchConditionValue1TypedDict]],
)


CustomObjectRecordFilteredSearchConditionValue2 = TypeAliasType(
    "CustomObjectRecordFilteredSearchConditionValue2",
    Union[str, int, List[CustomObjectRecordFilteredSearchConditionValue1]],
)


class FieldKeyTypedDict(TypedDict):
    operator: NotRequired[str]
    value: NotRequired[CustomObjectRecordFilteredSearchConditionValue2TypedDict]


class FieldKey(BaseModel):
    operator: Optional[str] = None

    value: Optional[CustomObjectRecordFilteredSearchConditionValue2] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["operator", "value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CustomObjectRecordFilteredSearchConditionTypedDict(TypedDict):
    field_key: NotRequired[Nullable[FieldKeyTypedDict]]


class CustomObjectRecordFilteredSearchCondition(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    field_key: OptionalNullable[FieldKey] = UNSET

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["field_key"])
        nullable_fields = set(["field_key"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        for k, v in serialized.items():
            m[k] = v

        return m
