"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class CustomFieldOptionObjectTypedDict(TypedDict):
    name: str
    r"""Name of the dropdown option"""
    value: str
    r"""Value of the dropdown option"""
    id: NotRequired[int]
    r"""Automatically assigned upon creation"""
    position: NotRequired[int]
    r"""Position of the dropdown option"""
    raw_name: NotRequired[str]
    r"""Raw name of the dropdown option"""
    url: NotRequired[str]
    r"""URL of the dropdown option"""


class CustomFieldOptionObject(BaseModel):
    name: str
    r"""Name of the dropdown option"""

    value: str
    r"""Value of the dropdown option"""

    id: Optional[int] = None
    r"""Automatically assigned upon creation"""

    position: Optional[int] = None
    r"""Position of the dropdown option"""

    raw_name: Optional[str] = None
    r"""Raw name of the dropdown option"""

    url: Optional[str] = None
    r"""URL of the dropdown option"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "position", "raw_name", "url"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
