"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Any, Dict, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class CustomObjectRecordInputTypedDict(TypedDict):
    custom_object_fields: NotRequired[Dict[str, Any]]
    external_id: NotRequired[Nullable[str]]
    r"""An id you can use to link custom object records to external data"""
    photo: NotRequired[Nullable[Dict[str, Any]]]
    r"""The record photo represented as an [Attachment](/api-reference/ticketing/tickets/ticket-attachments/). The `allows_photos` property must be set to `true` for the object"""


class CustomObjectRecordInput(BaseModel):
    custom_object_fields: Optional[Dict[str, Any]] = None

    external_id: OptionalNullable[str] = UNSET
    r"""An id you can use to link custom object records to external data"""

    photo: OptionalNullable[Dict[str, Any]] = UNSET
    r"""The record photo represented as an [Attachment](/api-reference/ticketing/tickets/ticket-attachments/). The `allows_photos` property must be set to `true` for the object"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["custom_object_fields", "external_id", "photo"])
        nullable_fields = set(["external_id", "photo"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
