"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class CustomObjectCreateInputTypedDict(TypedDict):
    key: NotRequired[str]
    r"""Unique identifier. Writable on create only"""
    title: NotRequired[str]
    r"""Display name for the object"""
    title_pluralized: NotRequired[str]
    r"""Pluralized version of the object's title"""


class CustomObjectCreateInput(BaseModel):
    key: Optional[str] = None
    r"""Unique identifier. Writable on create only"""

    title: Optional[str] = None
    r"""Display name for the object"""

    title_pluralized: Optional[str] = None
    r"""Pluralized version of the object's title"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["key", "title", "title_pluralized"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
