"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .customobjectrecord import CustomObjectRecord, CustomObjectRecordTypedDict
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class JobStatusTypedDict(TypedDict):
    id: NotRequired[str]
    message: NotRequired[Nullable[str]]
    progress: NotRequired[Nullable[int]]
    results: NotRequired[Nullable[List[CustomObjectRecordTypedDict]]]
    status: NotRequired[str]
    total: NotRequired[int]
    url: NotRequired[str]


class JobStatus(BaseModel):
    id: Optional[str] = None

    message: OptionalNullable[str] = UNSET

    progress: OptionalNullable[int] = UNSET

    results: OptionalNullable[List[CustomObjectRecord]] = UNSET

    status: Optional[str] = None

    total: Optional[int] = None

    url: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["id", "message", "progress", "results", "status", "total", "url"]
        )
        nullable_fields = set(["message", "progress", "results"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class CustomObjectRecordsJobsResponseTypedDict(TypedDict):
    job_status: NotRequired[JobStatusTypedDict]


class CustomObjectRecordsJobsResponse(BaseModel):
    job_status: Optional[JobStatus] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["job_status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
