"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .customobjectrecordfilteredsearchcondition import (
    CustomObjectRecordFilteredSearchCondition,
    CustomObjectRecordFilteredSearchConditionTypedDict,
)
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class CustomObjectRecordsFilteredSearchRequestBasicTypedDict(TypedDict):
    filter_: NotRequired[CustomObjectRecordFilteredSearchConditionTypedDict]


class CustomObjectRecordsFilteredSearchRequestBasic(BaseModel):
    filter_: Annotated[
        Optional[CustomObjectRecordFilteredSearchCondition],
        pydantic.Field(alias="filter"),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["filter"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
