"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class CustomObjectLimitsResponseTypedDict(TypedDict):
    count: NotRequired[int]
    r"""The current numnber of the requested resource"""
    limit: NotRequired[int]
    r"""The maximum allowed number for the requested resource"""


class CustomObjectLimitsResponse(BaseModel):
    count: Optional[int] = None
    r"""The current numnber of the requested resource"""

    limit: Optional[int] = None
    r"""The maximum allowed number for the requested resource"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["count", "limit"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
