"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .customobjectrecord_input import (
    CustomObjectRecordInput,
    CustomObjectRecordInputTypedDict,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class CustomObjectRecordsBulkCreateRequestJobTypedDict(TypedDict):
    action: NotRequired[str]
    items: NotRequired[List[CustomObjectRecordInputTypedDict]]
    r"""An array of record objects for job actions that create, update, or set. An array of strings for job actions that delete."""


class CustomObjectRecordsBulkCreateRequestJob(BaseModel):
    action: Optional[str] = None

    items: Optional[List[CustomObjectRecordInput]] = None
    r"""An array of record objects for job actions that create, update, or set. An array of strings for job actions that delete."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["action", "items"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CustomObjectRecordsBulkCreateRequestTypedDict(TypedDict):
    job: NotRequired[CustomObjectRecordsBulkCreateRequestJobTypedDict]


class CustomObjectRecordsBulkCreateRequest(BaseModel):
    job: Optional[CustomObjectRecordsBulkCreateRequestJob] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["job"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
