"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .customobjectrecord import CustomObjectRecord, CustomObjectRecordTypedDict
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, Nullable, UNSET_SENTINEL


class CustomObjectRecordsResponseLinksTypedDict(TypedDict):
    next: Nullable[str]
    prev: Nullable[str]


class CustomObjectRecordsResponseLinks(BaseModel):
    next: Nullable[str]

    prev: Nullable[str]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class CustomObjectRecordsResponseMetaTypedDict(TypedDict):
    after_cursor: Nullable[str]
    before_cursor: Nullable[str]
    has_more: bool


class CustomObjectRecordsResponseMeta(BaseModel):
    after_cursor: Nullable[str]

    before_cursor: Nullable[str]

    has_more: bool

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class CustomObjectRecordsResponseTypedDict(TypedDict):
    count: NotRequired[int]
    r"""The number of results returned for the current request"""
    custom_object_records: NotRequired[List[CustomObjectRecordTypedDict]]
    links: NotRequired[CustomObjectRecordsResponseLinksTypedDict]
    meta: NotRequired[CustomObjectRecordsResponseMetaTypedDict]


class CustomObjectRecordsResponse(BaseModel):
    count: Optional[int] = None
    r"""The number of results returned for the current request"""

    custom_object_records: Optional[List[CustomObjectRecord]] = None

    links: Optional[CustomObjectRecordsResponseLinks] = None

    meta: Optional[CustomObjectRecordsResponseMeta] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["count", "custom_object_records", "links", "meta"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
