"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class ConditionsAllOperatorTypedDict(TypedDict):
    terminal: NotRequired[bool]
    title: NotRequired[str]
    value: NotRequired[str]


class ConditionsAllOperator(BaseModel):
    terminal: Optional[bool] = None

    title: Optional[str] = None

    value: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["terminal", "title", "value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ConditionsAllValueTypedDict(TypedDict):
    enabled: NotRequired[bool]
    title: NotRequired[str]
    value: NotRequired[str]


class ConditionsAllValue(BaseModel):
    enabled: Optional[bool] = None

    title: Optional[str] = None

    value: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["enabled", "title", "value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class DefinitionsResponseConditionsAllTypedDict(TypedDict):
    group: NotRequired[str]
    nullable: NotRequired[bool]
    operators: NotRequired[List[ConditionsAllOperatorTypedDict]]
    repeatable: NotRequired[bool]
    subject: NotRequired[str]
    title: NotRequired[str]
    type: NotRequired[str]
    values: NotRequired[List[ConditionsAllValueTypedDict]]


class DefinitionsResponseConditionsAll(BaseModel):
    group: Optional[str] = None

    nullable: Optional[bool] = None

    operators: Optional[List[ConditionsAllOperator]] = None

    repeatable: Optional[bool] = None

    subject: Optional[str] = None

    title: Optional[str] = None

    type: Optional[str] = None

    values: Optional[List[ConditionsAllValue]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "group",
                "nullable",
                "operators",
                "repeatable",
                "subject",
                "title",
                "type",
                "values",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ConditionsAnyOperatorTypedDict(TypedDict):
    terminal: NotRequired[bool]
    title: NotRequired[str]
    value: NotRequired[str]


class ConditionsAnyOperator(BaseModel):
    terminal: Optional[bool] = None

    title: Optional[str] = None

    value: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["terminal", "title", "value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ConditionsAnyValueTypedDict(TypedDict):
    enabled: NotRequired[bool]
    title: NotRequired[str]
    value: NotRequired[str]


class ConditionsAnyValue(BaseModel):
    enabled: Optional[bool] = None

    title: Optional[str] = None

    value: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["enabled", "title", "value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class DefinitionsResponseConditionsAnyTypedDict(TypedDict):
    group: NotRequired[str]
    nullable: NotRequired[bool]
    operators: NotRequired[List[ConditionsAnyOperatorTypedDict]]
    repeatable: NotRequired[bool]
    subject: NotRequired[str]
    title: NotRequired[str]
    type: NotRequired[str]
    values: NotRequired[List[ConditionsAnyValueTypedDict]]


class DefinitionsResponseConditionsAny(BaseModel):
    group: Optional[str] = None

    nullable: Optional[bool] = None

    operators: Optional[List[ConditionsAnyOperator]] = None

    repeatable: Optional[bool] = None

    subject: Optional[str] = None

    title: Optional[str] = None

    type: Optional[str] = None

    values: Optional[List[ConditionsAnyValue]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "group",
                "nullable",
                "operators",
                "repeatable",
                "subject",
                "title",
                "type",
                "values",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class DefinitionsResponseDefinitionsTypedDict(TypedDict):
    conditions_all: NotRequired[List[DefinitionsResponseConditionsAllTypedDict]]
    conditions_any: NotRequired[List[DefinitionsResponseConditionsAnyTypedDict]]


class DefinitionsResponseDefinitions(BaseModel):
    conditions_all: Optional[List[DefinitionsResponseConditionsAll]] = None

    conditions_any: Optional[List[DefinitionsResponseConditionsAny]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["conditions_all", "conditions_any"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class DefinitionsResponseTypedDict(TypedDict):
    definitions: NotRequired[DefinitionsResponseDefinitionsTypedDict]


class DefinitionsResponse(BaseModel):
    definitions: Optional[DefinitionsResponseDefinitions] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["definitions"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
