"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing_extensions import TypedDict
from zendesk.types import BaseModel, Nullable, UNSET_SENTINEL


class DeletedUserObjectPhotoTypedDict(TypedDict):
    pass


class DeletedUserObjectPhoto(BaseModel):
    pass


class DeletedUserObjectTypedDict(TypedDict):
    active: bool
    created_at: str
    email: str
    id: int
    locale: str
    locale_id: int
    name: str
    organization_id: int
    phone: Nullable[str]
    photo: Nullable[DeletedUserObjectPhotoTypedDict]
    role: str
    shared_phone_number: Nullable[str]
    time_zone: str
    updated_at: str
    url: str


class DeletedUserObject(BaseModel):
    active: bool

    created_at: str

    email: str

    id: int

    locale: str

    locale_id: int

    name: str

    organization_id: int

    phone: Nullable[str]

    photo: Nullable[DeletedUserObjectPhoto]

    role: str

    shared_phone_number: Nullable[str]

    time_zone: str

    updated_at: str

    url: str

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
