"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .conditionsobject import ConditionsObject, ConditionsObjectTypedDict
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class DeletionScheduleInputTypedDict(TypedDict):
    active: NotRequired[bool]
    r"""Whether the deletion schedule is active"""
    conditions: NotRequired[ConditionsObjectTypedDict]
    r"""An object that describes the conditions under which the automation will execute. See [Conditions reference](/documentation/ticketing/reference-guides/conditions-reference)"""
    description: NotRequired[str]
    r"""The description of the deletion schedule"""
    title: NotRequired[str]
    r"""The title of the deletion schedule"""


class DeletionScheduleInput(BaseModel):
    active: Optional[bool] = None
    r"""Whether the deletion schedule is active"""

    conditions: Optional[ConditionsObject] = None
    r"""An object that describes the conditions under which the automation will execute. See [Conditions reference](/documentation/ticketing/reference-guides/conditions-reference)"""

    description: Optional[str] = None
    r"""The description of the deletion schedule"""

    title: Optional[str] = None
    r"""The title of the deletion schedule"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["active", "conditions", "description", "title"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
