"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


EmailCCObjectAction = Literal[
    "put",
    "delete",
]


class EmailCCObjectTypedDict(TypedDict):
    action: NotRequired[EmailCCObjectAction]
    user_email: NotRequired[str]
    user_id: NotRequired[str]
    user_name: NotRequired[str]


class EmailCCObject(BaseModel):
    action: Optional[EmailCCObjectAction] = None

    user_email: Optional[str] = None

    user_id: Optional[str] = None

    user_name: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["action", "user_email", "user_id", "user_name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
