"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .emailnotificationobject import (
    EmailNotificationObject,
    EmailNotificationObjectTypedDict,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class EmailNotificationsResponseTypedDict(TypedDict):
    email_notifications: NotRequired[List[EmailNotificationObjectTypedDict]]


class EmailNotificationsResponse(BaseModel):
    email_notifications: Optional[List[EmailNotificationObject]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["email_notifications"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
