"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class ErrorLinksTypedDict(TypedDict):
    pass


class ErrorLinks(BaseModel):
    pass


class ErrorSourceTypedDict(TypedDict):
    pass


class ErrorSource(BaseModel):
    pass


class ErrorTypedDict(TypedDict):
    code: str
    title: str
    detail: NotRequired[str]
    id: NotRequired[str]
    links: NotRequired[ErrorLinksTypedDict]
    source: NotRequired[ErrorSourceTypedDict]
    status: NotRequired[str]


class Error(BaseModel):
    code: str

    title: str

    detail: Optional[str] = None

    id: Optional[str] = None

    links: Optional[ErrorLinks] = None

    source: Optional[ErrorSource] = None

    status: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["detail", "id", "links", "source", "status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
