"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class GroupMembershipObjectTypedDict(TypedDict):
    group_id: int
    r"""The id of a group"""
    user_id: int
    r"""The id of an agent"""
    created_at: NotRequired[datetime]
    r"""The time the group was created"""
    default: NotRequired[bool]
    r"""If true, tickets assigned directly to the agent will assume this membership's group"""
    id: NotRequired[int]
    r"""Automatically assigned upon creation"""
    updated_at: NotRequired[datetime]
    r"""The time of the last update of the group"""
    url: NotRequired[str]
    r"""The API url of this record"""


class GroupMembershipObject(BaseModel):
    group_id: int
    r"""The id of a group"""

    user_id: int
    r"""The id of an agent"""

    created_at: Optional[datetime] = None
    r"""The time the group was created"""

    default: Optional[bool] = None
    r"""If true, tickets assigned directly to the agent will assume this membership's group"""

    id: Optional[int] = None
    r"""Automatically assigned upon creation"""

    updated_at: Optional[datetime] = None
    r"""The time of the last update of the group"""

    url: Optional[str] = None
    r"""The API url of this record"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["created_at", "default", "id", "updated_at", "url"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
