"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class GroupSLAPolicyFilterDefinitionResponseOperatorTypedDict(TypedDict):
    title: NotRequired[str]
    value: NotRequired[str]


class GroupSLAPolicyFilterDefinitionResponseOperator(BaseModel):
    title: Optional[str] = None

    value: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["title", "value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GroupSLAPolicyFilterDefinitionResponseListTypedDict(TypedDict):
    title: NotRequired[str]
    value: NotRequired[Nullable[int]]


class GroupSLAPolicyFilterDefinitionResponseList(BaseModel):
    title: Optional[str] = None

    value: OptionalNullable[int] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["title", "value"])
        nullable_fields = set(["value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class GroupSLAPolicyFilterDefinitionResponseValuesTypedDict(TypedDict):
    list: NotRequired[List[GroupSLAPolicyFilterDefinitionResponseListTypedDict]]
    type: NotRequired[str]


class GroupSLAPolicyFilterDefinitionResponseValues(BaseModel):
    list: Optional[List[GroupSLAPolicyFilterDefinitionResponseList]] = None

    type: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["list", "type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GroupSLAPolicyFilterDefinitionResponseAllTypedDict(TypedDict):
    group: NotRequired[str]
    operators: NotRequired[
        List[GroupSLAPolicyFilterDefinitionResponseOperatorTypedDict]
    ]
    title: NotRequired[str]
    value: NotRequired[str]
    values: NotRequired[GroupSLAPolicyFilterDefinitionResponseValuesTypedDict]


class GroupSLAPolicyFilterDefinitionResponseAll(BaseModel):
    group: Optional[str] = None

    operators: Optional[List[GroupSLAPolicyFilterDefinitionResponseOperator]] = None

    title: Optional[str] = None

    value: Optional[str] = None

    values: Optional[GroupSLAPolicyFilterDefinitionResponseValues] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["group", "operators", "title", "value", "values"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GroupSLAPolicyFilterDefinitionResponseDefinitionsTypedDict(TypedDict):
    all: NotRequired[List[GroupSLAPolicyFilterDefinitionResponseAllTypedDict]]


class GroupSLAPolicyFilterDefinitionResponseDefinitions(BaseModel):
    all: Optional[List[GroupSLAPolicyFilterDefinitionResponseAll]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["all"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GroupSLAPolicyFilterDefinitionResponseTypedDict(TypedDict):
    definitions: NotRequired[GroupSLAPolicyFilterDefinitionResponseDefinitionsTypedDict]


class GroupSLAPolicyFilterDefinitionResponse(BaseModel):
    definitions: Optional[GroupSLAPolicyFilterDefinitionResponseDefinitions] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["definitions"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
