"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL
from zendesk.utils import FieldMetadata, QueryParamMetadata


class GroupMembershipBulkDeleteRequestTypedDict(TypedDict):
    ids: NotRequired[str]
    r"""Id of the group memberships to delete. Comma separated"""


class GroupMembershipBulkDeleteRequest(BaseModel):
    ids: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Id of the group memberships to delete. Comma separated"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ids"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
