"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class HostMappingObjectTypedDict(TypedDict):
    cname: NotRequired[str]
    r"""The canonical name record for a host mapping"""
    expected_cnames: NotRequired[List[str]]
    r"""Array of expected CNAME records for host mapping(s) of a given brand"""
    is_valid: NotRequired[bool]
    r"""Whether a host mapping is valid or not for a given brand"""
    reason: NotRequired[str]
    r"""Reason why a host mapping is valid or not"""


class HostMappingObject(BaseModel):
    cname: Optional[str] = None
    r"""The canonical name record for a host mapping"""

    expected_cnames: Optional[List[str]] = None
    r"""Array of expected CNAME records for host mapping(s) of a given brand"""

    is_valid: Optional[bool] = None
    r"""Whether a host mapping is valid or not for a given brand"""

    reason: Optional[str] = None
    r"""Reason why a host mapping is valid or not"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["cname", "expected_cnames", "is_valid", "reason"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
