"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .incrementalskillbasedroutingattribute import (
    IncrementalSkillBasedRoutingAttribute,
    IncrementalSkillBasedRoutingAttributeTypedDict,
)
from .incrementalskillbasedroutingattributevalue import (
    IncrementalSkillBasedRoutingAttributeValue,
    IncrementalSkillBasedRoutingAttributeValueTypedDict,
)
from .incrementalskillbasedroutinginstancevalue import (
    IncrementalSkillBasedRoutingInstanceValue,
    IncrementalSkillBasedRoutingInstanceValueTypedDict,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class IncrementalSkillBasedRoutingTypedDict(TypedDict):
    attribute_values: NotRequired[
        List[IncrementalSkillBasedRoutingAttributeValueTypedDict]
    ]
    r"""Routing attribute values"""
    attributes: NotRequired[List[IncrementalSkillBasedRoutingAttributeTypedDict]]
    r"""Routing attributes"""
    count: NotRequired[int]
    r"""The number of results returned for the current request"""
    end_time: NotRequired[int]
    r"""The most recent resource creation time present in this result set in Unix epoch time"""
    instance_values: NotRequired[
        List[IncrementalSkillBasedRoutingInstanceValueTypedDict]
    ]
    r"""Routing instance values"""
    next_page: NotRequired[str]
    r"""The URL that should be called to get the next set of results"""


class IncrementalSkillBasedRouting(BaseModel):
    attribute_values: Optional[List[IncrementalSkillBasedRoutingAttributeValue]] = None
    r"""Routing attribute values"""

    attributes: Optional[List[IncrementalSkillBasedRoutingAttribute]] = None
    r"""Routing attributes"""

    count: Optional[int] = None
    r"""The number of results returned for the current request"""

    end_time: Optional[int] = None
    r"""The most recent resource creation time present in this result set in Unix epoch time"""

    instance_values: Optional[List[IncrementalSkillBasedRoutingInstanceValue]] = None
    r"""Routing instance values"""

    next_page: Optional[str] = None
    r"""The URL that should be called to get the next set of results"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "attribute_values",
                "attributes",
                "count",
                "end_time",
                "instance_values",
                "next_page",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
