"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from typing import Callable, List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL
from zendesk.utils import FieldMetadata, QueryParamMetadata


class ListTriggerCategoriesPageTypedDict(TypedDict):
    r"""Pagination parameters"""

    after: NotRequired[str]
    before: NotRequired[str]
    size: NotRequired[int]


class ListTriggerCategoriesPage(BaseModel):
    r"""Pagination parameters"""

    after: Annotated[Optional[str], FieldMetadata(query=True)] = None

    before: Annotated[Optional[str], FieldMetadata(query=True)] = None

    size: Annotated[Optional[int], FieldMetadata(query=True)] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["after", "before", "size"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


ListTriggerCategoriesSort = Literal[
    "position",
    "-position",
    "name",
    "-name",
    "created_at",
    "-created_at",
    "updated_at",
    "-updated_at",
]
r"""Sort parameters"""


Include = Literal["rule_counts",]
r"""Allowed sideloads"""


class ListTriggerCategoriesRequestTypedDict(TypedDict):
    page_before: NotRequired[str]
    r"""A [pagination cursor](/documentation/api-basics/pagination/paginating-through-lists-using-cursor-pagination) that tells the endpoint which page to start on. It should be a `meta.before_cursor` value from a previous request. Note: `page[before]` and `page[after]` can't be used together in the same request.

    """
    page_after: NotRequired[str]
    r"""A [pagination cursor](/documentation/api-basics/pagination/paginating-through-lists-using-cursor-pagination) that tells the endpoint which page to start on. It should be a `meta.after_cursor` value from a previous request. Note: `page[before]` and `page[after]` can't be used together in the same request.

    """
    page_size: NotRequired[int]
    r"""Specifies how many records should be returned in the response. You can specify up to 100 records per page.

    """
    page: NotRequired[ListTriggerCategoriesPageTypedDict]
    r"""Pagination parameters"""
    sort: NotRequired[ListTriggerCategoriesSort]
    r"""Sort parameters"""
    include: NotRequired[Include]
    r"""Allowed sideloads"""


class ListTriggerCategoriesRequest(BaseModel):
    page_before: Annotated[
        Optional[str],
        pydantic.Field(alias="page[before]"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""A [pagination cursor](/documentation/api-basics/pagination/paginating-through-lists-using-cursor-pagination) that tells the endpoint which page to start on. It should be a `meta.before_cursor` value from a previous request. Note: `page[before]` and `page[after]` can't be used together in the same request.

    """

    page_after: Annotated[
        Optional[str],
        pydantic.Field(alias="page[after]"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""A [pagination cursor](/documentation/api-basics/pagination/paginating-through-lists-using-cursor-pagination) that tells the endpoint which page to start on. It should be a `meta.after_cursor` value from a previous request. Note: `page[before]` and `page[after]` can't be used together in the same request.

    """

    page_size: Annotated[
        Optional[int],
        pydantic.Field(alias="page[size]"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 100
    r"""Specifies how many records should be returned in the response. You can specify up to 100 records per page.

    """

    page: Annotated[
        Optional[ListTriggerCategoriesPage],
        FieldMetadata(query=QueryParamMetadata(style="deepObject", explode=True)),
    ] = None
    r"""Pagination parameters"""

    sort: Annotated[
        Optional[ListTriggerCategoriesSort],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Sort parameters"""

    include: Annotated[
        Optional[Include],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Allowed sideloads"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["page[before]", "page[after]", "page[size]", "page", "sort", "include"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class TriggerCategoryRuleCountsTypedDict(TypedDict):
    active_count: NotRequired[int]
    inactive_count: NotRequired[int]
    created_at: NotRequired[str]
    id: NotRequired[str]
    name: NotRequired[str]
    position: NotRequired[int]
    updated_at: NotRequired[str]


class TriggerCategoryRuleCounts(BaseModel):
    active_count: Optional[int] = None

    inactive_count: Optional[int] = None

    created_at: Optional[str] = None

    id: Optional[str] = None

    name: Optional[str] = None

    position: Optional[int] = None

    updated_at: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "active_count",
                "inactive_count",
                "created_at",
                "id",
                "name",
                "position",
                "updated_at",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


ListTriggerCategoriesTriggerCategoryTypedDict = TriggerCategoryRuleCountsTypedDict


ListTriggerCategoriesTriggerCategory = TriggerCategoryRuleCounts


class ListTriggerCategoriesLinksTypedDict(TypedDict):
    next: NotRequired[str]
    prev: NotRequired[str]


class ListTriggerCategoriesLinks(BaseModel):
    next: Optional[str] = None

    prev: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["next", "prev"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListTriggerCategoriesMetaTypedDict(TypedDict):
    after_cursor: NotRequired[str]
    before_cursor: NotRequired[str]
    has_more: NotRequired[bool]


class ListTriggerCategoriesMeta(BaseModel):
    after_cursor: Optional[str] = None

    before_cursor: Optional[str] = None

    has_more: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["after_cursor", "before_cursor", "has_more"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListTriggerCategoriesResponseBodyTypedDict(TypedDict):
    r"""A paged array of ticket trigger categories"""

    trigger_categories: NotRequired[List[ListTriggerCategoriesTriggerCategoryTypedDict]]
    links: NotRequired[ListTriggerCategoriesLinksTypedDict]
    meta: NotRequired[ListTriggerCategoriesMetaTypedDict]


class ListTriggerCategoriesResponseBody(BaseModel):
    r"""A paged array of ticket trigger categories"""

    trigger_categories: Optional[List[ListTriggerCategoriesTriggerCategory]] = None

    links: Optional[ListTriggerCategoriesLinks] = None

    meta: Optional[ListTriggerCategoriesMeta] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["trigger_categories", "links", "meta"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListTriggerCategoriesResponseTypedDict(TypedDict):
    result: ListTriggerCategoriesResponseBodyTypedDict


class ListTriggerCategoriesResponse(BaseModel):
    next: Callable[[], Optional[ListTriggerCategoriesResponse]]

    result: ListTriggerCategoriesResponseBody
