"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL
from zendesk.utils import FieldMetadata, QueryParamMetadata


class ListViewsByIDRequestTypedDict(TypedDict):
    ids: str
    r"""List of view's ids separated by commas."""
    active: NotRequired[bool]
    r"""Only active views if true, inactive views if false"""


class ListViewsByIDRequest(BaseModel):
    ids: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""List of view's ids separated by commas."""

    active: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Only active views if true, inactive views if false"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["active"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
