"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class LocaleObjectTypedDict(TypedDict):
    created_at: NotRequired[datetime]
    r"""The ISO 8601 formatted date-time the locale was created"""
    id: NotRequired[int]
    r"""The unique ID of the locale"""
    locale: NotRequired[str]
    r"""The name of the locale"""
    name: NotRequired[str]
    r"""The name of the language"""
    updated_at: NotRequired[datetime]
    r"""The ISO 8601 formatted date-time when the locale was last updated"""
    url: NotRequired[str]
    r"""The URL of the locale record"""


class LocaleObject(BaseModel):
    created_at: Optional[datetime] = None
    r"""The ISO 8601 formatted date-time the locale was created"""

    id: Optional[int] = None
    r"""The unique ID of the locale"""

    locale: Optional[str] = None
    r"""The name of the locale"""

    name: Optional[str] = None
    r"""The name of the language"""

    updated_at: Optional[datetime] = None
    r"""The ISO 8601 formatted date-time when the locale was last updated"""

    url: Optional[str] = None
    r"""The URL of the locale record"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["created_at", "id", "locale", "name", "updated_at", "url"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
