"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class MacroApplyTicketResponseCommentTypedDict(TypedDict):
    body: NotRequired[str]
    public: NotRequired[bool]
    scoped_body: NotRequired[List[List[str]]]


class MacroApplyTicketResponseComment(BaseModel):
    body: Optional[str] = None

    public: Optional[bool] = None

    scoped_body: Optional[List[List[str]]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["body", "public", "scoped_body"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class FieldsTypedDict(TypedDict):
    id: NotRequired[int]
    value: NotRequired[str]


class Fields(BaseModel):
    id: Optional[int] = None

    value: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class MacroApplyTicketResponseTicketTypedDict(TypedDict):
    assignee_id: NotRequired[int]
    comment: NotRequired[MacroApplyTicketResponseCommentTypedDict]
    fields: NotRequired[FieldsTypedDict]
    group_id: NotRequired[int]
    id: NotRequired[int]
    url: NotRequired[str]


class MacroApplyTicketResponseTicket(BaseModel):
    assignee_id: Optional[int] = None

    comment: Optional[MacroApplyTicketResponseComment] = None

    fields: Optional[Fields] = None

    group_id: Optional[int] = None

    id: Optional[int] = None

    url: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["assignee_id", "comment", "fields", "group_id", "id", "url"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ResultTypedDict(TypedDict):
    ticket: NotRequired[MacroApplyTicketResponseTicketTypedDict]


class Result(BaseModel):
    ticket: Optional[MacroApplyTicketResponseTicket] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ticket"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class MacroApplyTicketResponseTypedDict(TypedDict):
    result: NotRequired[ResultTypedDict]


class MacroApplyTicketResponse(BaseModel):
    result: Optional[Result] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["result"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
