"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class ManySkillBasedRoutingAttributeValuesTypedDict(TypedDict):
    agent_id: NotRequired[int]
    r"""Id of the associated agent"""
    attribute_id: NotRequired[str]
    r"""Id of the associated attribute"""
    attribute_value_id: NotRequired[str]
    r"""Id of the associated attribute value"""
    created_at: NotRequired[datetime]
    r"""The time of creation of the instance value"""
    id: NotRequired[str]
    r"""Automatically assigned when an instance value is created"""
    name: NotRequired[str]
    r"""Name of the associated attribute value"""
    updated_at: NotRequired[datetime]
    r"""The time of the last update of the instance value"""
    url: NotRequired[str]
    r"""The URL of the associated attribute value"""


class ManySkillBasedRoutingAttributeValues(BaseModel):
    agent_id: Optional[int] = None
    r"""Id of the associated agent"""

    attribute_id: Optional[str] = None
    r"""Id of the associated attribute"""

    attribute_value_id: Optional[str] = None
    r"""Id of the associated attribute value"""

    created_at: Optional[datetime] = None
    r"""The time of creation of the instance value"""

    id: Optional[str] = None
    r"""Automatically assigned when an instance value is created"""

    name: Optional[str] = None
    r"""Name of the associated attribute value"""

    updated_at: Optional[datetime] = None
    r"""The time of the last update of the instance value"""

    url: Optional[str] = None
    r"""The URL of the associated attribute value"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "agent_id",
                "attribute_id",
                "attribute_value_id",
                "created_at",
                "id",
                "name",
                "updated_at",
                "url",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
