"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .manyskillbasedroutingattributevalues import (
    ManySkillBasedRoutingAttributeValues,
    ManySkillBasedRoutingAttributeValuesTypedDict,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class ManySkillBasedRoutingAttributeValuesResponseTypedDict(TypedDict):
    count: NotRequired[int]
    r"""The number of instance values returned"""
    instance_values: NotRequired[List[ManySkillBasedRoutingAttributeValuesTypedDict]]
    next_page: NotRequired[Nullable[str]]
    r"""The URL for the next page of results"""
    previous_page: NotRequired[Nullable[str]]
    r"""The URL for the previous page of results"""


class ManySkillBasedRoutingAttributeValuesResponse(BaseModel):
    count: Optional[int] = None
    r"""The number of instance values returned"""

    instance_values: Optional[List[ManySkillBasedRoutingAttributeValues]] = None

    next_page: OptionalNullable[str] = UNSET
    r"""The URL for the next page of results"""

    previous_page: OptionalNullable[str] = UNSET
    r"""The URL for the previous page of results"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["count", "instance_values", "next_page", "previous_page"]
        )
        nullable_fields = set(["next_page", "previous_page"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
