"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class ObjectTriggerConditionDefinitionObjectAnyOperatorTypedDict(TypedDict):
    format_: NotRequired[str]
    terminal: NotRequired[bool]
    title: NotRequired[str]
    value: NotRequired[str]


class ObjectTriggerConditionDefinitionObjectAnyOperator(BaseModel):
    format_: Annotated[Optional[str], pydantic.Field(alias="format")] = None

    terminal: Optional[bool] = None

    title: Optional[str] = None

    value: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["format", "terminal", "title", "value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ObjectTriggerConditionDefinitionObjectAnyValueTypedDict(TypedDict):
    enabled: NotRequired[bool]
    title: NotRequired[str]
    value: NotRequired[str]


class ObjectTriggerConditionDefinitionObjectAnyValue(BaseModel):
    enabled: Optional[bool] = None

    title: Optional[str] = None

    value: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["enabled", "title", "value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ObjectTriggerConditionDefinitionObjectAnyTypedDict(TypedDict):
    group: NotRequired[str]
    nullable: NotRequired[bool]
    operators: NotRequired[
        List[ObjectTriggerConditionDefinitionObjectAnyOperatorTypedDict]
    ]
    repeatable: NotRequired[bool]
    subject: NotRequired[str]
    title: NotRequired[str]
    type: NotRequired[str]
    values: NotRequired[List[ObjectTriggerConditionDefinitionObjectAnyValueTypedDict]]


class ObjectTriggerConditionDefinitionObjectAny(BaseModel):
    group: Optional[str] = None

    nullable: Optional[bool] = None

    operators: Optional[List[ObjectTriggerConditionDefinitionObjectAnyOperator]] = None

    repeatable: Optional[bool] = None

    subject: Optional[str] = None

    title: Optional[str] = None

    type: Optional[str] = None

    values: Optional[List[ObjectTriggerConditionDefinitionObjectAnyValue]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "group",
                "nullable",
                "operators",
                "repeatable",
                "subject",
                "title",
                "type",
                "values",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
