"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .objecttriggerobject_input import (
    ObjectTriggerObjectInput,
    ObjectTriggerObjectInputTypedDict,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class ObjectTriggerRequestTypedDict(TypedDict):
    trigger: NotRequired[ObjectTriggerObjectInputTypedDict]


class ObjectTriggerRequest(BaseModel):
    trigger: Optional[ObjectTriggerObjectInput] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["trigger"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
