"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .objecttriggeractiondefinitionobject import (
    ObjectTriggerActionDefinitionObject,
    ObjectTriggerActionDefinitionObjectTypedDict,
)
from .objecttriggerconditiondefinitionobjectall import (
    ObjectTriggerConditionDefinitionObjectAll,
    ObjectTriggerConditionDefinitionObjectAllTypedDict,
)
from .objecttriggerconditiondefinitionobjectany import (
    ObjectTriggerConditionDefinitionObjectAny,
    ObjectTriggerConditionDefinitionObjectAnyTypedDict,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class ObjectTriggerDefinitionObjectTypedDict(TypedDict):
    actions: NotRequired[List[ObjectTriggerActionDefinitionObjectTypedDict]]
    conditions_all: NotRequired[
        List[ObjectTriggerConditionDefinitionObjectAllTypedDict]
    ]
    conditions_any: NotRequired[
        List[ObjectTriggerConditionDefinitionObjectAnyTypedDict]
    ]


class ObjectTriggerDefinitionObject(BaseModel):
    actions: Optional[List[ObjectTriggerActionDefinitionObject]] = None

    conditions_all: Optional[List[ObjectTriggerConditionDefinitionObjectAll]] = None

    conditions_any: Optional[List[ObjectTriggerConditionDefinitionObjectAny]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["actions", "conditions_all", "conditions_any"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
