"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class OrganizationMergeRequestOrganizationMergeTypedDict(TypedDict):
    winner_id: NotRequired[int]
    r"""The id of the winning organization."""


class OrganizationMergeRequestOrganizationMerge(BaseModel):
    winner_id: Optional[int] = None
    r"""The id of the winning organization."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["winner_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class OrganizationMergeRequestTypedDict(TypedDict):
    organization_merge: NotRequired[OrganizationMergeRequestOrganizationMergeTypedDict]


class OrganizationMergeRequest(BaseModel):
    organization_merge: Optional[OrganizationMergeRequestOrganizationMerge] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["organization_merge"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
