"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class PaginationMetaTypedDict(TypedDict):
    has_more: NotRequired[bool]
    r"""Whether there are more results available"""
    after_cursor: NotRequired[str]
    r"""Cursor for the next page of results"""
    before_cursor: NotRequired[str]
    r"""Cursor for the previous page of results"""
    count: NotRequired[int]
    r"""Total number of items (may not always be present)"""


class PaginationMeta(BaseModel):
    has_more: Optional[bool] = None
    r"""Whether there are more results available"""

    after_cursor: Optional[str] = None
    r"""Cursor for the next page of results"""

    before_cursor: Optional[str] = None
    r"""Cursor for the previous page of results"""

    count: Optional[int] = None
    r"""Total number of items (may not always be present)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["has_more", "after_cursor", "before_cursor", "count"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
