"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .triggerconditiondefinitionobjectall import (
    TriggerConditionDefinitionObjectAll,
    TriggerConditionDefinitionObjectAllTypedDict,
)
from .triggerconditiondefinitionobjectany import (
    TriggerConditionDefinitionObjectAny,
    TriggerConditionDefinitionObjectAnyTypedDict,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class RelationshipFilterDefinitionTypedDict(TypedDict):
    conditions_all: NotRequired[List[TriggerConditionDefinitionObjectAllTypedDict]]
    conditions_any: NotRequired[List[TriggerConditionDefinitionObjectAnyTypedDict]]


class RelationshipFilterDefinition(BaseModel):
    conditions_all: Optional[List[TriggerConditionDefinitionObjectAll]] = None

    conditions_any: Optional[List[TriggerConditionDefinitionObjectAny]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["conditions_all", "conditions_any"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
