"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL
from zendesk.utils import FieldMetadata, QueryParamMetadata


class ReorderSLAPoliciesRequestTypedDict(TypedDict):
    sla_policy_ids: NotRequired[List[int]]
    r"""The IDs of the SLA Policies to reorder"""


class ReorderSLAPoliciesRequest(BaseModel):
    sla_policy_ids: Annotated[
        Optional[List[int]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The IDs of the SLA Policies to reorder"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["sla_policy_ids"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
