"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .resourcecollectionobject import (
    ResourceCollectionObject,
    ResourceCollectionObjectTypedDict,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class ResourceCollectionResponseTypedDict(TypedDict):
    resource_collection: NotRequired[ResourceCollectionObjectTypedDict]


class ResourceCollectionResponse(BaseModel):
    resource_collection: Optional[ResourceCollectionObject] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["resource_collection"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
