"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class ResourceTypedDict(TypedDict):
    deleted: NotRequired[bool]
    identifier: NotRequired[str]
    resource_id: NotRequired[int]
    type: NotRequired[str]


class Resource(BaseModel):
    deleted: Optional[bool] = None

    identifier: Optional[str] = None

    resource_id: Optional[int] = None

    type: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["deleted", "identifier", "resource_id", "type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ResourceCollectionObjectTypedDict(TypedDict):
    created_at: NotRequired[datetime]
    r"""When the resource collection was created"""
    id: NotRequired[int]
    r"""id for the resource collection. Automatically assigned upon creation"""
    resources: NotRequired[List[ResourceTypedDict]]
    r"""Array of resource metadata objects. See [Resource objects](#resource-objects)"""
    updated_at: NotRequired[datetime]
    r"""Last time the resource collection was updated"""


class ResourceCollectionObject(BaseModel):
    created_at: Optional[datetime] = None
    r"""When the resource collection was created"""

    id: Optional[int] = None
    r"""id for the resource collection. Automatically assigned upon creation"""

    resources: Optional[List[Resource]] = None
    r"""Array of resource metadata objects. See [Resource objects](#resource-objects)"""

    updated_at: Optional[datetime] = None
    r"""Last time the resource collection was updated"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["created_at", "id", "resources", "updated_at"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
