"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class SatisfactionReasonObjectTypedDict(TypedDict):
    value: str
    r"""Translated value of the reason in the account locale"""
    created_at: NotRequired[datetime]
    r"""The time the reason was created"""
    deleted_at: NotRequired[datetime]
    r"""The time the reason was deleted"""
    id: NotRequired[int]
    r"""Automatically assigned upon creation"""
    raw_value: NotRequired[str]
    r"""The dynamic content placeholder, if present, or the current \"value\", if not. See [Dynamic Content Items](/api-reference/ticketing/ticket-management/dynamic_content/)"""
    reason_code: NotRequired[int]
    r"""An account-level code for referencing the reason. Custom reasons are assigned an auto-incrementing integer (non-system reason codes begin at 1000). See [Reason codes](#reason-codes)"""
    updated_at: NotRequired[datetime]
    r"""The time the reason was updated"""
    url: NotRequired[str]
    r"""API URL for the resource"""


class SatisfactionReasonObject(BaseModel):
    value: str
    r"""Translated value of the reason in the account locale"""

    created_at: Optional[datetime] = None
    r"""The time the reason was created"""

    deleted_at: Optional[datetime] = None
    r"""The time the reason was deleted"""

    id: Optional[int] = None
    r"""Automatically assigned upon creation"""

    raw_value: Optional[str] = None
    r"""The dynamic content placeholder, if present, or the current \"value\", if not. See [Dynamic Content Items](/api-reference/ticketing/ticket-management/dynamic_content/)"""

    reason_code: Optional[int] = None
    r"""An account-level code for referencing the reason. Custom reasons are assigned an auto-incrementing integer (non-system reason codes begin at 1000). See [Reason codes](#reason-codes)"""

    updated_at: Optional[datetime] = None
    r"""The time the reason was updated"""

    url: Optional[str] = None
    r"""API URL for the resource"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "created_at",
                "deleted_at",
                "id",
                "raw_value",
                "reason_code",
                "updated_at",
                "url",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
