"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .searchresultobject import SearchResultObject, SearchResultObjectTypedDict
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class SearchResponseTypedDict(TypedDict):
    count: NotRequired[int]
    r"""The number of resources returned by the query corresponding to this page of results in the paginated response"""
    facets: NotRequired[Nullable[str]]
    r"""The facets corresponding to the search query"""
    next_page: NotRequired[Nullable[str]]
    r"""URL to the next page of results"""
    previous_page: NotRequired[Nullable[str]]
    r"""URL to the previous page of results"""
    results: NotRequired[List[SearchResultObjectTypedDict]]
    r"""May consist of tickets, users, groups, or organizations, as specified by the `result_type` property in each result object"""


class SearchResponse(BaseModel):
    count: Optional[int] = None
    r"""The number of resources returned by the query corresponding to this page of results in the paginated response"""

    facets: OptionalNullable[str] = UNSET
    r"""The facets corresponding to the search query"""

    next_page: OptionalNullable[str] = UNSET
    r"""URL to the next page of results"""

    previous_page: OptionalNullable[str] = UNSET
    r"""URL to the previous page of results"""

    results: Optional[List[SearchResultObject]] = None
    r"""May consist of tickets, users, groups, or organizations, as specified by the `result_type` property in each result object"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["count", "facets", "next_page", "previous_page", "results"]
        )
        nullable_fields = set(["facets", "next_page", "previous_page"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
