"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class SearchResultObjectTypedDict(TypedDict):
    created_at: NotRequired[str]
    r"""When the resource was created"""
    default: NotRequired[bool]
    r"""Flag to indicate whether this is the default resource"""
    deleted: NotRequired[bool]
    r"""Flag to indicate whether or not resource has been deleted"""
    description: NotRequired[str]
    r"""The description of the resource"""
    id: NotRequired[int]
    r"""The ID of the resource"""
    name: NotRequired[str]
    r"""The name of the resource"""
    result_type: NotRequired[str]
    r"""The type of the resource"""
    updated_at: NotRequired[str]
    r"""When the resource was last updated"""
    url: NotRequired[str]
    r"""The url of the resource"""


class SearchResultObject(BaseModel):
    created_at: Optional[str] = None
    r"""When the resource was created"""

    default: Optional[bool] = None
    r"""Flag to indicate whether this is the default resource"""

    deleted: Optional[bool] = None
    r"""Flag to indicate whether or not resource has been deleted"""

    description: Optional[str] = None
    r"""The description of the resource"""

    id: Optional[int] = None
    r"""The ID of the resource"""

    name: Optional[str] = None
    r"""The name of the resource"""

    result_type: Optional[str] = None
    r"""The type of the resource"""

    updated_at: Optional[str] = None
    r"""When the resource was last updated"""

    url: Optional[str] = None
    r"""The url of the resource"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "created_at",
                "default",
                "deleted",
                "description",
                "id",
                "name",
                "result_type",
                "updated_at",
                "url",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
