"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class SessionObjectTypedDict(TypedDict):
    id: int
    r"""Automatically assigned when the session is created"""
    authenticated_at: NotRequired[Nullable[str]]
    r"""When the session was created"""
    last_seen_at: NotRequired[Nullable[str]]
    r"""The last approximate time this session was seen. This does not update on every request."""
    url: NotRequired[Nullable[str]]
    r"""The API URL of this session"""
    user_id: NotRequired[Nullable[int]]
    r"""The id of the user"""


class SessionObject(BaseModel):
    id: int
    r"""Automatically assigned when the session is created"""

    authenticated_at: OptionalNullable[str] = UNSET
    r"""When the session was created"""

    last_seen_at: OptionalNullable[str] = UNSET
    r"""The last approximate time this session was seen. This does not update on every request."""

    url: OptionalNullable[str] = UNSET
    r"""The API URL of this session"""

    user_id: OptionalNullable[int] = UNSET
    r"""The id of the user"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["authenticated_at", "last_seen_at", "url", "user_id"])
        nullable_fields = set(["authenticated_at", "last_seen_at", "url", "user_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
