"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .workspaceobject import WorkspaceObject, WorkspaceObjectTypedDict
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL
from zendesk.utils import FieldMetadata, PathParamMetadata


class ShowWorkspaceRequestTypedDict(TypedDict):
    workspace_id: int
    r"""The id of the workspace"""


class ShowWorkspaceRequest(BaseModel):
    workspace_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The id of the workspace"""


class ShowWorkspaceResponseTypedDict(TypedDict):
    r"""Successful response"""

    workspace: NotRequired[WorkspaceObjectTypedDict]


class ShowWorkspaceResponse(BaseModel):
    r"""Successful response"""

    workspace: Optional[WorkspaceObject] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["workspace"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
