"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class SkillBasedRoutingAttributeDefinitionsConditionsAllTypedDict(TypedDict):
    subject: NotRequired[str]
    title: NotRequired[str]


class SkillBasedRoutingAttributeDefinitionsConditionsAll(BaseModel):
    subject: Optional[str] = None

    title: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["subject", "title"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SkillBasedRoutingAttributeDefinitionsConditionsAnyTypedDict(TypedDict):
    subject: NotRequired[str]
    title: NotRequired[str]


class SkillBasedRoutingAttributeDefinitionsConditionsAny(BaseModel):
    subject: Optional[str] = None

    title: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["subject", "title"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SkillBasedRoutingAttributeDefinitionsDefinitionsTypedDict(TypedDict):
    conditions_all: NotRequired[
        List[SkillBasedRoutingAttributeDefinitionsConditionsAllTypedDict]
    ]
    conditions_any: NotRequired[
        List[SkillBasedRoutingAttributeDefinitionsConditionsAnyTypedDict]
    ]


class SkillBasedRoutingAttributeDefinitionsDefinitions(BaseModel):
    conditions_all: Optional[
        List[SkillBasedRoutingAttributeDefinitionsConditionsAll]
    ] = None

    conditions_any: Optional[
        List[SkillBasedRoutingAttributeDefinitionsConditionsAny]
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["conditions_all", "conditions_any"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SkillBasedRoutingAttributeDefinitionsTypedDict(TypedDict):
    definitions: NotRequired[SkillBasedRoutingAttributeDefinitionsDefinitionsTypedDict]


class SkillBasedRoutingAttributeDefinitions(BaseModel):
    definitions: Optional[SkillBasedRoutingAttributeDefinitionsDefinitions] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["definitions"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
