"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .attachmentobject import AttachmentObject, AttachmentObjectTypedDict
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class SuspendedTicketsAttachmentsResponseUploadTypedDict(TypedDict):
    attachments: NotRequired[List[AttachmentObjectTypedDict]]
    token: NotRequired[str]
    r"""Token for subsequent request"""


class SuspendedTicketsAttachmentsResponseUpload(BaseModel):
    attachments: Optional[List[AttachmentObject]] = None

    token: Optional[str] = None
    r"""Token for subsequent request"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["attachments", "token"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SuspendedTicketsAttachmentsResponseTypedDict(TypedDict):
    upload: NotRequired[SuspendedTicketsAttachmentsResponseUploadTypedDict]


class SuspendedTicketsAttachmentsResponse(BaseModel):
    upload: Optional[SuspendedTicketsAttachmentsResponseUpload] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["upload"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
