"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class SuspendedTicketsExportResponseExportTypedDict(TypedDict):
    status: NotRequired[str]
    view_id: NotRequired[str]


class SuspendedTicketsExportResponseExport(BaseModel):
    status: Optional[str] = None

    view_id: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["status", "view_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SuspendedTicketsExportResponseTypedDict(TypedDict):
    export: NotRequired[SuspendedTicketsExportResponseExportTypedDict]


class SuspendedTicketsExportResponse(BaseModel):
    export: Optional[SuspendedTicketsExportResponseExport] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["export"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
