"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .suspendedticketobject import SuspendedTicketObject, SuspendedTicketObjectTypedDict
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class SuspendedTicketsResponseTypedDict(TypedDict):
    suspended_tickets: NotRequired[List[SuspendedTicketObjectTypedDict]]


class SuspendedTicketsResponse(BaseModel):
    suspended_tickets: Optional[List[SuspendedTicketObject]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["suspended_tickets"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
