"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class SystemFieldOptionObjectTypedDict(TypedDict):
    name: NotRequired[str]
    r"""Name of the system field option"""
    value: NotRequired[str]
    r"""Value of the system field option"""


class SystemFieldOptionObject(BaseModel):
    name: Optional[str] = None
    r"""Name of the system field option"""

    value: Optional[str] = None
    r"""Value of the system field option"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name", "value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
