"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class TagCountObjectTypedDict(TypedDict):
    refreshed_at: NotRequired[str]
    r"""The time that the count value was last refreshed"""
    value: NotRequired[int]
    r"""The count of tags created in the last 24 hours"""


class TagCountObject(BaseModel):
    refreshed_at: Optional[str] = None
    r"""The time that the count value was last refreshed"""

    value: Optional[int] = None
    r"""The count of tags created in the last 24 hours"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["refreshed_at", "value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
