"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .ticketbulkimportrequest import (
    TicketBulkImportRequest,
    TicketBulkImportRequestTypedDict,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL
from zendesk.utils import FieldMetadata, QueryParamMetadata, RequestMetadata


class TicketBulkImportRequestRequestTypedDict(TypedDict):
    archive_immediately: NotRequired[bool]
    r"""If `true`, any ticket created with a `closed` status bypasses the normal ticket lifecycle and will be created directly in your ticket archive"""
    ticket_bulk_import_request: NotRequired[TicketBulkImportRequestTypedDict]


class TicketBulkImportRequestRequest(BaseModel):
    archive_immediately: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""If `true`, any ticket created with a `closed` status bypasses the normal ticket lifecycle and will be created directly in your ticket archive"""

    ticket_bulk_import_request: Annotated[
        Optional[TicketBulkImportRequest],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["archive_immediately", "TicketBulkImportRequest"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
