"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class TicketFormStatusesUpdateParamsTypedDict(TypedDict):
    destroy: NotRequired[str]
    r"""If set to a value of \\"1\\" and an id value is passed, the server will delete the record"""
    custom_status_id: NotRequired[int]
    id: NotRequired[str]


class TicketFormStatusesUpdateParams(BaseModel):
    destroy: Annotated[Optional[str], pydantic.Field(alias="_destroy")] = None
    r"""If set to a value of \\"1\\" and an id value is passed, the server will delete the record"""

    custom_status_id: Optional[int] = None

    id: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["_destroy", "custom_status_id", "id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
