"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class TicketCommentsCountResponseCountTypedDict(TypedDict):
    refreshed_at: NotRequired[datetime]
    value: NotRequired[int]


class TicketCommentsCountResponseCount(BaseModel):
    refreshed_at: Optional[datetime] = None

    value: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["refreshed_at", "value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class TicketCommentsCountResponseTypedDict(TypedDict):
    count: NotRequired[TicketCommentsCountResponseCountTypedDict]


class TicketCommentsCountResponse(BaseModel):
    count: Optional[TicketCommentsCountResponseCount] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["count"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
