"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .auditobject import AuditObject, AuditObjectTypedDict
from .ticketobject import TicketObject, TicketObjectTypedDict
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class TicketUpdateResponseTypedDict(TypedDict):
    audit: NotRequired[AuditObjectTypedDict]
    ticket: NotRequired[TicketObjectTypedDict]


class TicketUpdateResponse(BaseModel):
    audit: Optional[AuditObject] = None

    ticket: Optional[TicketObject] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["audit", "ticket"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
