"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class TicketFormStatusObjectTypedDict(TypedDict):
    custom_status_id: NotRequired[int]
    r"""The id of the associated custom status"""
    id: NotRequired[str]
    r"""Automatically assigned when creating a ticket form"""
    ticket_form_id: NotRequired[int]
    r"""The id of the associated ticket form"""


class TicketFormStatusObject(BaseModel):
    custom_status_id: Optional[int] = None
    r"""The id of the associated custom status"""

    id: Optional[str] = None
    r"""Automatically assigned when creating a ticket form"""

    ticket_form_id: Optional[int] = None
    r"""The id of the associated ticket form"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["custom_status_id", "id", "ticket_form_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
