"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .ticketobject import TicketObject, TicketObjectTypedDict
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class TimeBasedExportIncrementalTicketsResponseTypedDict(TypedDict):
    r"""See [Tickets](/api-reference/ticketing/tickets/tickets/) for a detailed example."""

    count: NotRequired[int]
    end_of_stream: NotRequired[bool]
    end_time: NotRequired[int]
    next_page: NotRequired[Nullable[str]]
    tickets: NotRequired[List[TicketObjectTypedDict]]


class TimeBasedExportIncrementalTicketsResponse(BaseModel):
    r"""See [Tickets](/api-reference/ticketing/tickets/tickets/) for a detailed example."""

    count: Optional[int] = None

    end_of_stream: Optional[bool] = None

    end_time: Optional[int] = None

    next_page: OptionalNullable[str] = UNSET

    tickets: Optional[List[TicketObject]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["count", "end_of_stream", "end_time", "next_page", "tickets"]
        )
        nullable_fields = set(["next_page"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
