"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .triggeractiondiffobject import (
    TriggerActionDiffObject,
    TriggerActionDiffObjectTypedDict,
)
from .triggerchangeobject import TriggerChangeObject, TriggerChangeObjectTypedDict
from .triggerconditiondiffobject import (
    TriggerConditionDiffObject,
    TriggerConditionDiffObjectTypedDict,
)
from .triggersnapshotobject import TriggerSnapshotObject, TriggerSnapshotObjectTypedDict
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class DiffTypedDict(TypedDict):
    actions: NotRequired[List[TriggerActionDiffObjectTypedDict]]
    r"""An array that contain [action diff objects](#Action Diffs)"""
    active: NotRequired[List[TriggerChangeObjectTypedDict]]
    r"""An array of [change](#change) objects"""
    conditions: NotRequired[TriggerConditionDiffObjectTypedDict]
    description: NotRequired[List[TriggerChangeObjectTypedDict]]
    r"""An array of [change](#change) objects"""
    source_id: NotRequired[int]
    r"""ID of the source revision"""
    target_id: NotRequired[int]
    r"""ID of the target revision"""
    title: NotRequired[List[TriggerChangeObjectTypedDict]]
    r"""An array of [change](#change) objects"""


class Diff(BaseModel):
    actions: Optional[List[TriggerActionDiffObject]] = None
    r"""An array that contain [action diff objects](#Action Diffs)"""

    active: Optional[List[TriggerChangeObject]] = None
    r"""An array of [change](#change) objects"""

    conditions: Optional[TriggerConditionDiffObject] = None

    description: Optional[List[TriggerChangeObject]] = None
    r"""An array of [change](#change) objects"""

    source_id: Optional[int] = None
    r"""ID of the source revision"""

    target_id: Optional[int] = None
    r"""ID of the target revision"""

    title: Optional[List[TriggerChangeObject]] = None
    r"""An array of [change](#change) objects"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "actions",
                "active",
                "conditions",
                "description",
                "source_id",
                "target_id",
                "title",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class TriggerRevisionsResponseTriggerRevisionTypedDict(TypedDict):
    author_id: NotRequired[int]
    created_at: NotRequired[str]
    diff: NotRequired[DiffTypedDict]
    id: NotRequired[int]
    snapshot: NotRequired[TriggerSnapshotObjectTypedDict]
    url: NotRequired[str]


class TriggerRevisionsResponseTriggerRevision(BaseModel):
    author_id: Optional[int] = None

    created_at: Optional[str] = None

    diff: Optional[Diff] = None

    id: Optional[int] = None

    snapshot: Optional[TriggerSnapshotObject] = None

    url: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["author_id", "created_at", "diff", "id", "snapshot", "url"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class TriggerRevisionsResponseTypedDict(TypedDict):
    after_cursor: NotRequired[str]
    after_url: NotRequired[str]
    before_cursor: NotRequired[str]
    before_url: NotRequired[str]
    count: NotRequired[int]
    trigger_revisions: NotRequired[
        List[TriggerRevisionsResponseTriggerRevisionTypedDict]
    ]


class TriggerRevisionsResponse(BaseModel):
    after_cursor: Optional[str] = None

    after_url: Optional[str] = None

    before_cursor: Optional[str] = None

    before_url: Optional[str] = None

    count: Optional[int] = None

    trigger_revisions: Optional[List[TriggerRevisionsResponseTriggerRevision]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "after_cursor",
                "after_url",
                "before_cursor",
                "before_url",
                "count",
                "trigger_revisions",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
