"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class TriggerBulkUpdateItemTypedDict(TypedDict):
    id: int
    r"""The ID of the ticket trigger to update"""
    active: NotRequired[bool]
    r"""The active status of the ticket trigger (true or false)"""
    category_id: NotRequired[str]
    r"""The ID of the new category the ticket trigger is to be moved to"""
    position: NotRequired[int]
    r"""The new position of the ticket trigger"""


class TriggerBulkUpdateItem(BaseModel):
    id: int
    r"""The ID of the ticket trigger to update"""

    active: Optional[bool] = None
    r"""The active status of the ticket trigger (true or false)"""

    category_id: Optional[str] = None
    r"""The ID of the new category the ticket trigger is to be moved to"""

    position: Optional[int] = None
    r"""The new position of the ticket trigger"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["active", "category_id", "position"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
