"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class TriggerConditionDefinitionObjectAnyOperatorTypedDict(TypedDict):
    terminal: NotRequired[bool]
    title: NotRequired[str]
    value: NotRequired[str]


class TriggerConditionDefinitionObjectAnyOperator(BaseModel):
    terminal: Optional[bool] = None

    title: Optional[str] = None

    value: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["terminal", "title", "value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class TriggerConditionDefinitionObjectAnyTypedDict(TypedDict):
    group: NotRequired[str]
    nullable: NotRequired[bool]
    operators: NotRequired[List[TriggerConditionDefinitionObjectAnyOperatorTypedDict]]
    repeatable: NotRequired[bool]
    subject: NotRequired[str]
    title: NotRequired[str]
    type: NotRequired[str]


class TriggerConditionDefinitionObjectAny(BaseModel):
    group: Optional[str] = None

    nullable: Optional[bool] = None

    operators: Optional[List[TriggerConditionDefinitionObjectAnyOperator]] = None

    repeatable: Optional[bool] = None

    subject: Optional[str] = None

    title: Optional[str] = None

    type: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["group", "nullable", "operators", "repeatable", "subject", "title", "type"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
