"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class TwitterChannelTwicketStatusResponseStatusTypedDict(TypedDict):
    favorited: NotRequired[bool]
    id: NotRequired[int]
    retweeted: NotRequired[bool]
    user_followed: NotRequired[bool]


class TwitterChannelTwicketStatusResponseStatus(BaseModel):
    favorited: Optional[bool] = None

    id: Optional[int] = None

    retweeted: Optional[bool] = None

    user_followed: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["favorited", "id", "retweeted", "user_followed"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class TwitterChannelTwicketStatusResponseTypedDict(TypedDict):
    statuses: NotRequired[List[TwitterChannelTwicketStatusResponseStatusTypedDict]]


class TwitterChannelTwicketStatusResponse(BaseModel):
    statuses: Optional[List[TwitterChannelTwicketStatusResponseStatus]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["statuses"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
