"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .deletionschedule import DeletionSchedule, DeletionScheduleTypedDict
from .deletionschedule_input import (
    DeletionScheduleInput,
    DeletionScheduleInputTypedDict,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL
from zendesk.utils import FieldMetadata, PathParamMetadata, RequestMetadata


class UpdateDeletionScheduleRequestBodyTypedDict(TypedDict):
    deletion_schedule: NotRequired[DeletionScheduleInputTypedDict]


class UpdateDeletionScheduleRequestBody(BaseModel):
    deletion_schedule: Optional[DeletionScheduleInput] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["deletion_schedule"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UpdateDeletionScheduleRequestTypedDict(TypedDict):
    deletion_schedule_id: int
    r"""The id of the deletion schedule"""
    request_body: UpdateDeletionScheduleRequestBodyTypedDict


class UpdateDeletionScheduleRequest(BaseModel):
    deletion_schedule_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The id of the deletion schedule"""

    request_body: Annotated[
        UpdateDeletionScheduleRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class UpdateDeletionScheduleResponseTypedDict(TypedDict):
    r"""Success Response"""

    deletion_schedule: NotRequired[DeletionScheduleTypedDict]


class UpdateDeletionScheduleResponse(BaseModel):
    r"""Success Response"""

    deletion_schedule: Optional[DeletionSchedule] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["deletion_schedule"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
