"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updateticketformstatusesparams import (
    UpdateTicketFormStatusesParams,
    UpdateTicketFormStatusesParamsTypedDict,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL
from zendesk.utils import FieldMetadata, PathParamMetadata, RequestMetadata


class UpdateTicketFormStatusesRequestTypedDict(TypedDict):
    ticket_form_id: int
    r"""The ID of the ticket form"""
    update_ticket_form_statuses_params: NotRequired[
        UpdateTicketFormStatusesParamsTypedDict
    ]


class UpdateTicketFormStatusesRequest(BaseModel):
    ticket_form_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the ticket form"""

    update_ticket_form_statuses_params: Annotated[
        Optional[UpdateTicketFormStatusesParams],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["UpdateTicketFormStatusesParams"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
