"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .customstatusupdaterequest import (
    CustomStatusUpdateRequest,
    CustomStatusUpdateRequestTypedDict,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL
from zendesk.utils import FieldMetadata, PathParamMetadata, RequestMetadata


class UpdateCustomStatusRequestTypedDict(TypedDict):
    custom_status_id: int
    r"""The id of the custom status"""
    custom_status_update_request: NotRequired[CustomStatusUpdateRequestTypedDict]


class UpdateCustomStatusRequest(BaseModel):
    custom_status_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The id of the custom status"""

    custom_status_update_request: Annotated[
        Optional[CustomStatusUpdateRequest],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["CustomStatusUpdateRequest"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
