"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .workspaceinput import WorkspaceInput, WorkspaceInputTypedDict
from .workspaceobject import WorkspaceObject, WorkspaceObjectTypedDict
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL
from zendesk.utils import FieldMetadata, PathParamMetadata, RequestMetadata


class UpdateWorkspaceRequestBodyTypedDict(TypedDict):
    workspace: NotRequired[WorkspaceInputTypedDict]


class UpdateWorkspaceRequestBody(BaseModel):
    workspace: Optional[WorkspaceInput] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["workspace"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UpdateWorkspaceRequestTypedDict(TypedDict):
    workspace_id: int
    r"""The id of the workspace"""
    request_body: NotRequired[UpdateWorkspaceRequestBodyTypedDict]


class UpdateWorkspaceRequest(BaseModel):
    workspace_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The id of the workspace"""

    request_body: Annotated[
        Optional[UpdateWorkspaceRequestBody],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["RequestBody"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UpdateWorkspaceResponseTypedDict(TypedDict):
    r"""OK"""

    workspace: NotRequired[WorkspaceObjectTypedDict]


class UpdateWorkspaceResponse(BaseModel):
    r"""OK"""

    workspace: Optional[WorkspaceObject] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["workspace"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
