"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .brandupdaterequest import BrandUpdateRequest, BrandUpdateRequestTypedDict
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL
from zendesk.utils import FieldMetadata, PathParamMetadata, RequestMetadata


class UpdateBrandRequestTypedDict(TypedDict):
    brand_id: int
    r"""The ID of the brand"""
    brand_update_request: NotRequired[BrandUpdateRequestTypedDict]


class UpdateBrandRequest(BaseModel):
    brand_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the brand"""

    brand_update_request: Annotated[
        Optional[BrandUpdateRequest],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["BrandUpdateRequest"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
