"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class UserRelatedObjectTypedDict(TypedDict):
    assigned_tickets: NotRequired[int]
    r"""Count of assigned tickets"""
    ccd_tickets: NotRequired[int]
    r"""Count of collaborated tickets"""
    organization_subscriptions: NotRequired[int]
    r"""Count of organization subscriptions"""
    requested_tickets: NotRequired[int]
    r"""Count of requested tickets"""


class UserRelatedObject(BaseModel):
    assigned_tickets: Optional[int] = None
    r"""Count of assigned tickets"""

    ccd_tickets: Optional[int] = None
    r"""Count of collaborated tickets"""

    organization_subscriptions: Optional[int] = None
    r"""Count of organization subscriptions"""

    requested_tickets: Optional[int] = None
    r"""Count of requested tickets"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "assigned_tickets",
                "ccd_tickets",
                "organization_subscriptions",
                "requested_tickets",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
