"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import ConfigDict, model_serializer
from typing import Any, Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zendesk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class FromTypedDict(TypedDict):
    address: NotRequired[Nullable[str]]
    id: NotRequired[Nullable[int]]
    name: NotRequired[Nullable[str]]
    title: NotRequired[Nullable[str]]


class From(BaseModel):
    address: OptionalNullable[str] = UNSET

    id: OptionalNullable[int] = UNSET

    name: OptionalNullable[str] = UNSET

    title: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["address", "id", "name", "title"])
        nullable_fields = set(["address", "id", "name", "title"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class ToTypedDict(TypedDict):
    address: NotRequired[str]
    name: NotRequired[str]


class To(BaseModel):
    address: Optional[str] = None

    name: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["address", "name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ViaObjectSourceTypedDict(TypedDict):
    r"""For some channels a source object gives more information about how or why the ticket or event was created"""

    from_: NotRequired[FromTypedDict]
    rel: NotRequired[Nullable[str]]
    to: NotRequired[ToTypedDict]


class ViaObjectSource(BaseModel):
    r"""For some channels a source object gives more information about how or why the ticket or event was created"""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    from_: Annotated[Optional[From], pydantic.Field(alias="from")] = None

    rel: OptionalNullable[str] = UNSET

    to: Optional[To] = None

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["from", "rel", "to"])
        nullable_fields = set(["rel"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        for k, v in serialized.items():
            m[k] = v

        return m


class ViaObjectTypedDict(TypedDict):
    r"""An object explaining how the ticket was created. See the [Via object reference](/documentation/ticketing/reference-guides/via-object-reference)"""

    channel: NotRequired[str]
    r"""This tells you how the ticket or event was created. Examples: \"web\", \"mobile\", \"rule\", \"system\" 

    """
    source: NotRequired[ViaObjectSourceTypedDict]
    r"""For some channels a source object gives more information about how or why the ticket or event was created

    """


class ViaObject(BaseModel):
    r"""An object explaining how the ticket was created. See the [Via object reference](/documentation/ticketing/reference-guides/via-object-reference)"""

    channel: Optional[str] = None
    r"""This tells you how the ticket or event was created. Examples: \"web\", \"mobile\", \"rule\", \"system\" 

    """

    source: Optional[ViaObjectSource] = None
    r"""For some channels a source object gives more information about how or why the ticket or event was created

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["channel", "source"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
