"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .paginationlinks import PaginationLinks, PaginationLinksTypedDict
from .paginationmeta import PaginationMeta, PaginationMetaTypedDict
from .webhookinvocation import WebhookInvocation, WebhookInvocationTypedDict
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class WebhookInvocationListResponseTypedDict(TypedDict):
    invocations: NotRequired[List[WebhookInvocationTypedDict]]
    meta: NotRequired[PaginationMetaTypedDict]
    links: NotRequired[PaginationLinksTypedDict]


class WebhookInvocationListResponse(BaseModel):
    invocations: Optional[List[WebhookInvocation]] = None

    meta: Optional[PaginationMeta] = None

    links: Optional[PaginationLinks] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["invocations", "meta", "links"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
