"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


class TestTypedDict(TypedDict):
    __test__ = False  # pyright: ignore[reportGeneralTypeIssues]

    status: NotRequired[str]
    r"""Test status (e.g., \"success\", \"failed\")"""
    message: NotRequired[str]
    r"""Test result message"""
    response_code: NotRequired[int]
    r"""HTTP response code from the test endpoint"""
    response_body: NotRequired[str]
    r"""Response body from the test endpoint"""


class Test(BaseModel):
    __test__ = False

    status: Optional[str] = None
    r"""Test status (e.g., \"success\", \"failed\")"""

    message: Optional[str] = None
    r"""Test result message"""

    response_code: Optional[int] = None
    r"""HTTP response code from the test endpoint"""

    response_body: Optional[str] = None
    r"""Response body from the test endpoint"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["status", "message", "response_code", "response_body"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class WebhookTestResponseTypedDict(TypedDict):
    test: NotRequired[TestTypedDict]


class WebhookTestResponse(BaseModel):
    test: Optional[Test] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["test"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
