"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel, UNSET_SENTINEL


WebhookInvocationStatus = Literal[
    "unknown",
    "accepted",
    "success",
    "failed",
    "timeout",
    "circuit broken",
    "throttled",
    "client error",
    "server error",
]
r"""Status of the webhook invocation"""


class WebhookInvocationTypedDict(TypedDict):
    id: NotRequired[str]
    r"""Unique invocation identifier"""
    webhook_id: NotRequired[str]
    r"""ID of the webhook that was invoked"""
    status: NotRequired[WebhookInvocationStatus]
    r"""Status of the webhook invocation"""
    created_at: NotRequired[datetime]
    r"""When the invocation was created"""
    latest_completed_at: NotRequired[datetime]
    r"""When the invocation was last completed"""
    event_type: NotRequired[str]
    r"""Type of event that triggered the webhook"""
    attempts_count: NotRequired[int]
    r"""Number of delivery attempts made"""


class WebhookInvocation(BaseModel):
    id: Optional[str] = None
    r"""Unique invocation identifier"""

    webhook_id: Optional[str] = None
    r"""ID of the webhook that was invoked"""

    status: Optional[WebhookInvocationStatus] = None
    r"""Status of the webhook invocation"""

    created_at: Optional[datetime] = None
    r"""When the invocation was created"""

    latest_completed_at: Optional[datetime] = None
    r"""When the invocation was last completed"""

    event_type: Optional[str] = None
    r"""Type of event that triggered the webhook"""

    attempts_count: Optional[int] = None
    r"""Number of delivery attempts made"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "id",
                "webhook_id",
                "status",
                "created_at",
                "latest_completed_at",
                "event_type",
                "attempts_count",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
